INSERT INTO VAL PRO (CD_TAB FAT, SN ATIVO, DT VIGENCIA, CD PRO FAT, VL HONORARIO, VL OPERACIONAL, VL TOTAL)
SELECT 292, SN ATIVO, CD PRO FAT, VL HONORARIO, VL OPERACIONAL, VL TOTAL
FROM val pro WHERE cd tab fat = 106;

INSERT INTO VAL PORTE MEDICO (cd tab fat, cd PORTE MEDICO, DT VIGENCIA, VL PORTE MEDICO)
SELECT 292, cd PORTE MEDICO, DT VIGENCIA, VL PORTE MEDICO
FROM val PORTE MEDICO WHERE cd_tab_fat = 106;

INSERT INTO VAL PORTE (DT VIGENCIA, CD TAB FAT, CD POR ANE, VL PORTE)
SELECT DT VIGENCIA, 292, CD POR ANE, VL PORTE
FROM VAL PORTE WHERE CD_TAB_FAT = 106;

INSERT INTO FILME_TAB (CD_TAB FAT, CD PRO FAT, DT VIGENCIA, NR INCIDENCIAS, QT_M2_FILME)
SELECT 292, CD PRO FAT, DT VIGENCIA, NR INCIDENCIAS, QT_M2_FILME
FROM FILME_TAB WHERE CD_TAB_FAT = 106;

commit;