CREATE OR REPLACE PROCEDURE dbamv.prc_separa_consulta_sw
   IS

   CURSOR cContaA IS

   SELECT DISTINCT(A.CD_ATENDIMENTO), I.CD_REG_AMB, CONTA_X, X.CD_LANCAMENTO,
   i.CD_CON_PLA, i.CD_SETOR_PRODUZIU, i.CD_sETOR, x.CD_PRESTADOR, x.CD_ATI_MED, i.hr_lancamento
   ,Row_Number() OVER (PARTITION BY R.CD_REG_AMB ORDER BY R.CD_REG_AMB ASC)+Nvl(Y.CD_LANCAMENTO,0) CD_LANCAMENTO_NV
   FROM ATENDIME A
   INNER JOIN ITREG_AMB I ON I.CD_ATENDIMENTO = A.CD_ATENDIMENTO
                         AND I.CD_CONVENIO = A.CD_CONVENIO
    LEFT JOIN (SELECT DISTINCT(CD_REG_AMB) CONTA_X, CD_ATENDIMENTO, CD_LANCAMENTO, CD_PRESTADOR,CD_ATI_MED, QT_LANCAMENTO
               FROM ITREG_AMB I
               WHERE CD_PRO_FAT = '00105070')
                        X ON X.CD_ATENDIMENTO = I.CD_ATENDIMENTO
                         AND A.CD_ATENDIMENTO = X.CD_ATENDIMENTO
     LEFT JOIN (
                    SELECT I.CD_REG_AMB, Max(I.CD_LANCAMENTO) CD_LANCAMENTO
                    FROM ITREG_AMB I
                    INNER JOIN REG_AMB R ON R.CD_REG_AMB = I.CD_REG_AMB
                  --  WHERE I.CD_REG_fAT = 26
                    GROUP BY I.CD_REG_AMB
                  ) Y ON Y.CD_REG_AMB = I.CD_REG_AMB


   INNER JOIN REG_AMB R ON R.CD_REG_AMB = I.CD_REG_AMB

   WHERE A.TP_ATENDIMENTO = 'U'
     AND A.CD_CONVENIO = 8
     AND I.SN_FECHADA = 'N'
     AND I.CD_PRO_FAT = '02000027'
   -- AND A.CD_ATENDIMENTO = 1168120
    AND X.CONTA_X IS NULL

   GROUP BY A.CD_ATENDIMENTO, I.CD_REG_AMB, CONTA_X, X.CD_LANCAMENTO,
   i.CD_CON_PLA, i.CD_SETOR_PRODUZIU, i.CD_sETOR, x.CD_PRESTADOR, x.CD_ATI_MED, i.hr_lancamento
   ,R.CD_REG_AMB, Y.CD_LANCAMENTO
   ORDER BY 1 DESC
  ;

  r_ContaA cContaA%ROWTYPE;
  PROXIMA NUMBER(10,0);

   BEGIN

      OPEN cContaA;

        LOOP
        FETCH cContaA INTO r_ContaA;
        EXIT WHEN cContaA%NOTFOUND;

     iNSERT INTO itreg_amb (cd_reg_amb, CD_ATENDIMENTO, CD_CON_PLA, CD_CONVENIO, VL_TOTAL_CONTA, SN_FATURA_IMPRESSA, sn_fECHADA, VL_PERCENTUAL_MULTIPLA, CD_SETOR_PRODUZIU, CD_sETOR, SN_CONTA_cALCULADA, SN_PERTENCE_PACOTE, CD_PRESTADOR, CD_ATI_MED, hr_lancamento, QT_LANCAMENTO, VL_UNITARIO, VL_operacional_UNITARIO, CD_GRU_FAT, CD_LANCAMENTO, CD_PRO_FAT)
     VALUES (r_ContaA.CD_REG_AMB ,r_ContaA.CD_ATENDIMENTO, r_ContaA.CD_CON_PLA,8,0.01, 'N', 'N', 100, r_ContaA.CD_SETOR_PRODUZIU, r_ContaA.CD_sETOR, 'N', 'N', r_ContaA.CD_PRESTADOR, r_ContaA.CD_ATI_MED, r_ContaA.hr_lancamento,1, 0.01, 0, 7, r_ContaA.CD_LANCAMENTO_NV, '00105070');

      COMMIT;

 	SELECT seq_REG_AMB.NEXTVAL INTO  PROXIMA FROM DUAL;

   INSERT INTO REG_AMB (CD_REG_AMB, DT_LANCAMENTO, CD_CONVENIO, SN_FATURA_IMPRESSA, SN_FECHADA, DT_LANCAMENTO_FINAL, CD_MULTI_EMPRESA)
   VALUES (PROXIMA ,r_ContaA.HR_LANCAMENTO,8,'N','S',r_ContaA.HR_LANCAMENTO,1);

   UPDATE ITREG_AMB SET CD_REG_AMB = PROXIMA WHERE CD_PRO_FAT = '00105070' AND CD_REG_AMB = r_ContaA.CD_REG_AMB; --AND CD_LANCAMENTO = r_ContaA.CD_LANCAMENTO_NV;


   COMMIT;

  	   END LOOP;
     CLOSE cContaA;

  EXCEPTION
  WHEN OTHERS THEN
     raise_application_error(-20001, 'Ocorreu um erro no objeto! ');


  END;
/

