-- Select da tabela prestador
SELECT * FROM prestador


-- Visualizar todas colunas da tabela prestador
SELECT COLUMN_NAME
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'PRESTADOR';


-- Prestador Inativo c\ data de inativaçãoo
SELECT
    usu.CD_USUARIO,
    usu.NM_USUARIO,
    prest.TP_SITUACAO,
    prest.CD_PRESTADOR,
    prest.DT_INATIVACAO
FROM PRESTADOR prest
INNER JOIN USUARIOS usu
    ON prest.CD_PRESTADOR = usu.CD_PRESTADOR
WHERE prest.CD_TIP_PRESTA = '8'
  AND prest.TP_SITUACAO = 'I'  -- Filtra apenas os inativos
ORDER BY usu.NM_USUARIO;


-- Prestador Inativo c\ - seleciona pelo mês inativo.
SELECT
    usu.CD_USUARIO,
    usu.NM_USUARIO,
    prest.CD_PRESTADOR,
    CASE prest.TP_SITUACAO
        WHEN 'I' THEN 'Inativo'
    END AS TP_SITUACAO,
    prest.DT_CADASTRO,
    prest.DT_INATIVACAO
FROM PRESTADOR prest
INNER JOIN USUARIOS usu
    ON prest.CD_PRESTADOR = usu.CD_PRESTADOR
WHERE prest.CD_TIP_PRESTA = '8'
  AND prest.TP_SITUACAO = 'I'
  AND prest.DT_INATIVACAO BETWEEN TO_DATE('01/12/2023', 'DD/MM/YYYY') AND TO_DATE('28/02/2025', 'DD/MM/YYYY')
ORDER BY usu.NM_USUARIO;


-- Prestador ativo
SELECT
    usu.CD_USUARIO,
    usu.NM_USUARIO,
    prest.CD_PRESTADOR,
    prest.TP_SITUACAO
FROM PRESTADOR prest
INNER JOIN USUARIOS usu
    ON prest.CD_PRESTADOR = usu.CD_PRESTADOR
WHERE prest.CD_TIP_PRESTA = '8'
  AND prest.TP_SITUACAO = 'A' -- Filtra apenas os ativos
ORDER BY usu.NM_USUARIO;


-- Prestador ativo
/* substitui o valor 'A' pela palavra 'Ativo'
   tras a data dos cadastro - column dt_cadastro */
SELECT
    usu.CD_USUARIO,
    usu.NM_USUARIO,
    prest.CD_PRESTADOR,
    CASE
        WHEN prest.TP_SITUACAO = 'A' THEN 'Ativo'
        ELSE prest.TP_SITUACAO
    END AS TP_SITUACAO,  -- Inclui a tradu��o de 'A' diretamente aqui
    prest.DT_CADASTRO    -- Inclui a data do cadastro
FROM PRESTADOR prest
INNER JOIN USUARIOS usu
    ON prest.CD_PRESTADOR = usu.CD_PRESTADOR
WHERE prest.CD_TIP_PRESTA = '8'
  AND prest.TP_SITUACAO = 'A' --
ORDER BY usu.NM_USUARIO;


-- Prestador - Usuarios Ativos\Inativos c\ dt_cadastro e dt_inativacao
SELECT
    usu.CD_USUARIO,
    usu.NM_USUARIO,
    prest.CD_PRESTADOR,
    CASE prest.TP_SITUACAO
        WHEN 'A' THEN 'Ativo'
        WHEN 'I' THEN 'Inativo'
    END AS TP_SITUACAO,    -- Inclui a tradu��o de 'A' e 'I' diretamente aqui
    prest.DT_CADASTRO,     -- Inclui a data de cadastro
    prest.DT_INATIVACAO    -- Inclui a data de inativa��o
FROM PRESTADOR prest
INNER JOIN USUARIOS usu
    ON prest.CD_PRESTADOR = usu.CD_PRESTADOR
WHERE prest.CD_TIP_PRESTA = '8'
  AND prest.TP_SITUACAO IN ('A', 'I')  -- Filtra somente Ativos e Inativos
ORDER BY usu.NM_USUARIO;



/* Column_name 
CD_GRAU_INS
DT_CADASTRO_MANUAL
CD_NATURALIDADE
CD_ATIVIDADE_PRINCIPAL
CD_UF_ORGAO_EMISSOR
DT_EXPEDICAO_ORGAO_EMISSOR
DT_INICIO_CONTRATO
DT_FINAL_CONTRATO
CD_IDENTIFICADOR_PESSOA
CD_ENDERECO_POSTA
CD_ENDERECO_POSTA_COM
CD_AREA_ATUACAO
CD_CLUE_CONTRATO_NOMINA
CD_CLUE_CONTRATO_REAL
CD_JORNADA
SN_RESIDENCIA_MEDICA
CD_ANO_RESIDENCIA
CD_ESPECIALID_RESIDENTE
VL_SALARIO
CD_INSTITUICAO_EXTERNA
TIPO_MODALIDADE_CONTRATO
SN_FIEL
SN_VIGENCIA_FIEL
TP_CONTRATO_EXTERNO
DS_ORIENTACAO_AGENDAMENTO_WEB
CD_ESTADO_FORMACAO
CD_PRESTADOR
CD_BANCO
CD_CONSELHO
CD_TIP_PRESTA
NR_CPF_CGC
TP_SITUACAO
NM_PRESTADOR
NM_MNEMONICO
TP_CORPO_CLINICO
CD_PRESTADOR_MUITOS
DS_EMAIL
DS_ENDERECO
DS_CODIGO_CONSELHO
DS_FACULDADE
DT_CADASTRO
DT_NASCIMENTO
NR_FONE_COMERCIAL
NR_FONE_CONTATO
NR_CEP
NR_AGENCIA
NM_AGENCIA
NR_CONTA
CD_CIDADE
SN_REPASSE_FATURA_AMB_SUS
SN_ANESTESISTA
SN_AUXILIAR
SN_CIRURGIAO
SN_OUTROS
CD_REG_REPASSE
CD_PRESTADOR_REPASSE
DS_OBS
TP_VINCULO
DS_BAIRRO
NR_INSS
NR_CCM
CD_REG_REPASSE_SIA
DS_COMPLEMENTO
NR_DOCUMENTO
DS_ENDERECO_COMERCIAL
DS_BAIRRO_COMERCIAL
CD_CIDADE_COMERCIAL
DS_COMPLEMENTO_COMERCIAL
DS_CEP_COMERCIAL
FOTO
SN_ATUANTE
TP_DOCUMENTACAO
DS_ATRIBUTO1
SN_ALT_DADOS_ORA_APP
NR_PISPASEP
INSCR_AUTONOMO
NM_MAE
NM_PAI
CD_FORNECEDOR
CD_MULTI_EMPRESA
CD_INDICE
DS_SENHA_PRE_INTERNACAO
SN_ADMINISTRADOR_PRESTADOR
DS_CARGO
CD_PRESTADOR_INTEGRA
DT_INTEGRA
CD_SEQ_INTEGRA
DT_INATIVACAO
CD_IDENTIFICACAO
NR_CNS
DT_CAD_COOPERATIVA
NR_MATRICULA_COOPERATIVA
CD_REG_REPASSE_SIH
TP_CAT_PRE_SUS
NR_CAT_PRE_SUS
SN_CESSAO_CREDITO
SN_AUDITOR_SUS
DT_INICIO_ATUACAO
CD_SETOR
TP_PRESTADOR
CD_TIPO_LOGRADOURO
NR_ENDERECO
CD_TIPO_LOGRADOURO_COMERCIAL
NR_ENDERECO_COMERCIAL
NR_CNES
CD_CBOS
TP_ACESSO_DIAGNOSTICO
DS_ORIENTACAO_AGENDAMENTO
SN_MOSTRA_ENDERECO
SN_MOSTRA_ENDERECO_COM
TP_REMESSA
DS_SIGLA_AGENDAMENTO
DV_AGENCIA
DV_CONTA_CORRENTE
NR_PONTUACAO_OCORRENCIA
CD_SITUACAO_FAMILIAR
TP_SEXO
TP_COR
TP_CERTIDAO
DS_OM_IDENTIDADE
CD_CIDADANIA
CD_IDENTIDADE_GENERO
SN_LIBERA_ACESSO_LISTA_PEP
NR_PONTUACAO
NM_SOCIAL_PACIENTE
DT_NATURALIZACAO
DS_PASSAPORTE
CD_PAIS_EMISSAO_PAS
DT_EMISSAO_PAS
DT_VALIDADE_PAS
*/