 Select tp_grupo_setor
                       , cd_setor
                       , nm_setor
                       , cd_cen_cus
                       , sn_pode_solicitar_exames
                       , cd_fator
                       , cd_grupo_de_custo
                       , cd_setor_custo
                       , nr_ordem_rateio
                       , sn_centro_de_custo
                       , classificacao
                       , cd_multi_empresa
                       , tp_rat_mat_diretos
                       , sn_aceita_lancamento
                       , cd_rotina
                       , sn_producao_faturada
                       , sn_calculo_evento
                       , tp_composicao_calculo
                       , cd_rotina_mat_diretos
                       , cd_seq_resumo
                       , cd_seq_detalhe
                       , sn_deducao_honorario
                       , sn_exporta_ffis
                       , sn_ativo
                       , ds_caminho_impressora
                       , cd_setor_exportacao
                       , sn_imprime_laudo_local
                       , ds_impressora_etiq_coleta
                       , tp_setor
                       , cd_multi_empresa_origem
                       , tp_calculo_honorario
                       , sn_ver_exame_n_liberado
                       , cd_setor_integra
                       , ds_sigla_agendamento
                    From setor
                   Where cd_setor = 1 );
