-- Alterar a data de atendimento

select *
  from atendime
where cd_atendimento = 1144504;


-- DESABILITAR
ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_ATENDIMENTO DISABLE;
ALTER TRIGGER MVINTEGRA.TRG_IMVW_OUT_ATENDIMENTO DISABLE;



UPDATE atendime
SET
  dt_atendimento  = TO_TIMESTAMP('17/03/2026 14:44', 'DD/MM/YYYY HH24:MI'),
  hr_atendimento  = TO_TIMESTAMP('17/01/2026 14:44', 'DD/MM/YYYY HH24:MI')
WHERE cd_atendimento = 1144504;


-- HABILITAR
ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_ATENDIMENTO ENABLE;
ALTER TRIGGER MVINTEGRA.TRG_IMVW_OUT_ATENDIMENTO ENABLE;



-- VALIDAR STATUS
SELECT
    OWNER,
    TRIGGER_NAME,
    STATUS,
    TRIGGER_TYPE,
    TRIGGERING_EVENT,
    TABLE_NAME
FROM DBA_TRIGGERS
WHERE TRIGGER_NAME IN (
    'TRG_IMVW_SAI_ATENDIMENTO',
    'TRG_IMVW_OUT_ATENDIMENTO'
)
ORDER BY TRIGGER_NAME;