-- Quantidade de Atendimentos por Mês 

SELECT 
    TO_CHAR(a.DT_ATENDIMENTO, 'YYYY-MM') AS ANO_MES,
    EXTRACT(YEAR FROM a.DT_ATENDIMENTO) AS ANO,
    EXTRACT(MONTH FROM a.DT_ATENDIMENTO) AS MES,
    COUNT(DISTINCT a.CD_PACIENTE) AS QUANTIDADE_PACIENTES,
    COUNT(a.CD_ATENDIMENTO) AS QUANTIDADE_ATENDIMENTOS
FROM 
    DBAMV.ATENDIME a
INNER JOIN 
    DBAMV.PACIENTE pac ON a.CD_PACIENTE = pac.CD_PACIENTE
WHERE 
    a.DT_ATENDIMENTO >= TO_DATE('01/01/2021', 'DD/MM/YYYY')
    AND a.DT_ATENDIMENTO < ADD_MONTHS(TO_DATE('01/03/2025', 'DD/MM/YYYY'), 1)
GROUP BY 
    TO_CHAR(a.DT_ATENDIMENTO, 'YYYY-MM'),
    EXTRACT(YEAR FROM a.DT_ATENDIMENTO),
    EXTRACT(MONTH FROM a.DT_ATENDIMENTO)
ORDER BY 
    ANO_MES ASC;
