select *
  from atendime
where cd_atendimento = 1060179;


ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_ATENDIMENTO DISABLE;
ALTER TRIGGER MVINTEGRA.TRG_IMVW_OUT_ATENDIMENTO DISABLE;


UPDATE atendime
SET
  dt_atendimento  = TO_TIMESTAMP('07/08/2025 14:07', 'DD/MM/YYYY HH24:MI'),
  hr_atendimento  = TO_TIMESTAMP('07/08/2025 14:07', 'DD/MM/YYYY HH24:MI')
WHERE cd_atendimento = 1060179;


ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_ATENDIMENTO ENABLE;
ALTER TRIGGER MVINTEGRA.TRG_IMVW_OUT_ATENDIMENTO ENABLE;








