-- SELECT PARA VALIDAR QUAIS USU�RIOS POSSUEM E N�O POSSUEM UM DETERMINADO SETOR
WITH usuarios_esperados AS (
  SELECT 'SALATIEL.ROCHA' AS cd_id_usuario FROM dual UNION ALL
  SELECT 'ANA.PATRICIO' FROM dual UNION ALL
  SELECT 'ALINE.MARGRAF' FROM dual UNION ALL
  SELECT 'ANA.DINIZ' FROM dual UNION ALL
  SELECT 'ANDERSON.SILVA' FROM dual UNION ALL
  SELECT 'EMILLY.SILVA' FROM dual UNION ALL
  SELECT 'FERNANDA.SLIMA' FROM dual UNION ALL
  SELECT 'GABRIELLA.SILVA' FROM dual UNION ALL
  SELECT 'GIOVANNA.RAMOS' FROM dual UNION ALL
  SELECT 'JAMYLE.CORDEIRO' FROM dual UNION ALL
  SELECT 'KELLY.SILVERIO' FROM dual UNION ALL
  SELECT 'LUCAS.LEONARDO' FROM dual UNION ALL
  SELECT 'NADRIA.MATOS' FROM dual UNION ALL
  SELECT 'TAMILLY.SANTOS' FROM dual UNION ALL
  SELECT 'THAMYS.RAYMUNDO' FROM dual UNION ALL
  SELECT 'WESLLEY.SANTOS' FROM dual UNION ALL
  SELECT 'WILLIAM.JESUS' FROM dual UNION ALL
  SELECT 'GABRIELLA.LEITE' FROM dual UNION ALL
  SELECT 'KAMILLA.SILVA' FROM dual UNION ALL
  SELECT 'WALLISON.LARA' FROM dual UNION ALL
  SELECT 'EMERSON.BORGES' FROM dual UNION ALL
  SELECT 'ERIVAN.GAMA' FROM dual UNION ALL
  SELECT 'JHOSEPH.LINDOSO' FROM dual UNION ALL
  SELECT 'JULIA.MOREIRA' FROM dual UNION ALL
  SELECT 'LUIZA.SIENNA' FROM dual UNION ALL
  SELECT 'PRISCILA.SCHROTH' FROM dual UNION ALL
  SELECT 'SOLIMAR.FILHO' FROM dual UNION ALL
  SELECT 'THALISSA.MARTINS' FROM dual
)
SELECT
  ue.cd_id_usuario,
  CASE
    WHEN ui.cd_id_usuario IS NOT NULL THEN 'TEM SETOR 135'
    ELSE 'NAO TEM SETOR 135'
  END AS status_setor_135
FROM
  usuarios_esperados ue
LEFT JOIN
  usuario_unid_int ui
    ON ue.cd_id_usuario = ui.cd_id_usuario AND ui.cd_setor = '135'
ORDER BY
  ue.cd_id_usuario;


-- Lista somente os usuários nãoo tem o setor 135
WITH usuarios_esperados AS (
  SELECT 'SALATIEL.ROCHA' AS cd_id_usuario FROM dual UNION ALL
  SELECT 'ANA.PATRICIO' FROM dual UNION ALL
  SELECT 'ALINE.MARGRAF' FROM dual UNION ALL
  SELECT 'ANA.DINIZ' FROM dual UNION ALL
  SELECT 'ANDERSON.SILVA' FROM dual UNION ALL
  SELECT 'EMILLY.SILVA' FROM dual UNION ALL
  SELECT 'FERNANDA.SLIMA' FROM dual UNION ALL
  SELECT 'GABRIELLA.SILVA' FROM dual UNION ALL
  SELECT 'GIOVANNA.RAMOS' FROM dual UNION ALL
  SELECT 'JAMYLE.CORDEIRO' FROM dual UNION ALL
  SELECT 'KELLY.SILVERIO' FROM dual UNION ALL
  SELECT 'LUCAS.LEONARDO' FROM dual UNION ALL
  SELECT 'NADRIA.MATOS' FROM dual UNION ALL
  SELECT 'TAMILLY.SANTOS' FROM dual UNION ALL
  SELECT 'THAMYS.RAYMUNDO' FROM dual UNION ALL
  SELECT 'WESLLEY.SANTOS' FROM dual UNION ALL
  SELECT 'WILLIAM.JESUS' FROM dual UNION ALL
  SELECT 'GABRIELLA.LEITE' FROM dual UNION ALL
  SELECT 'KAMILLA.SILVA' FROM dual UNION ALL
  SELECT 'WALLISON.LARA' FROM dual UNION ALL
  SELECT 'EMERSON.BORGES' FROM dual UNION ALL
  SELECT 'ERIVAN.GAMA' FROM dual UNION ALL
  SELECT 'JHOSEPH.LINDOSO' FROM dual UNION ALL
  SELECT 'JULIA.MOREIRA' FROM dual UNION ALL
  SELECT 'LUIZA.SIENNA' FROM dual UNION ALL
  SELECT 'PRISCILA.SCHROTH' FROM dual UNION ALL
  SELECT 'SOLIMAR.FILHO' FROM dual UNION ALL
  SELECT 'THALISSA.MARTINS' FROM dual
)
SELECT
  ue.cd_id_usuario
FROM
  usuarios_esperados ue
LEFT JOIN
  usuario_unid_int ui
    ON ue.cd_id_usuario = ui.cd_id_usuario AND ui.cd_setor = '135'
WHERE
  ui.cd_id_usuario IS NULL
ORDER BY
  ue.cd_id_usuario;


