SELECT * FROM DBAMV.CONTAGEM
WHERE CD_CONTAGEM = 9489

SELECT SN_LOTE, SN_CONTROLE_VALIDADE, CD_PRODUTO FROM DBAMV.PRODUTO
WHERE CD_PRODUTO = 17662

SELECT * FROM DBAMV.LOT_PRO
WHERE CD_PRODUTO = 17662
AND QT_ESTOQUE_ATUAL > 0
