-- ADMPAC/M_CONFIGURACAO_PACIENTE

SELECT
    CD_SISTEMA,
    NM_COLUNA,
    SN_OBRIGA_COLUNA,
    CASE CD_SISTEMA
        WHEN 'SCMA' THEN 'CENTRAL DE AGENDAMENTO'
        WHEN 'PARA' THEN 'AMBULATÓRIO'
        WHEN 'PSSD' THEN 'LABORATÓRIO'
        WHEN 'PSDI' THEN 'DIAGNÓSTICO POR IMAGEM'
        WHEN 'PAEU' THEN 'URGÊNCIA'
        WHEN 'PARI' THEN 'INTERNAÇÃO'
        ELSE 'DESCONHECIDO'
    END AS DS_SISTEMA
FROM
    CONFIGURACAO_PACIENTE
WHERE
    CD_SISTEMA IN ('PAEU', 'PARI', 'PARA', 'PSDI', 'PSSD', 'SCMA')
    AND CD_MULTI_EMPRESA = 1
    AND NM_COLUNA = 'NR_CPF'
ORDER BY
    SN_OBRIGA_COLUNA DESC
    --FOR UPDATE