WITH ORDEM AS
 (SELECT F.CD_FAIXA_GUIA,
         RANK() OVER (PARTITION BY F.CD_CONVENIO, F.CD_MULTI_EMPRESA ORDER BY F.DT_VIGENCIA DESC, F.NR_FINAL DESC) AS RNK
    FROM DBAMV.FAIXA_GUIA_CONVENIO F
   ORDER BY 1 DESC)

SELECT CD_FAIXA_GUIA,
       CD_MULTI_EMPRESA,
       CD_CONVENIO,
       DT_VIGENCIA,
       NR_INICIAL,
       NR_FINAL,
       TP_GUIA,
       CASE WHEN RNK <> 1 THEN 0 ELSE QTD_TOTAL - QTD_UTILIZADA END AS GUIAS_RESTANTES

  FROM (SELECT FGC.CD_FAIXA_GUIA,
               FGC.CD_CONVENIO,
               FGC.CD_MULTI_EMPRESA,
               FGC.DT_VIGENCIA,
               FGC.NR_INICIAL,
               FGC.NR_FINAL,
               FGC.TP_GUIA,
               (FGC.NR_FINAL - FGC.NR_INICIAL) + 1AS QTD_TOTAL,
               (SELECT COUNT(IFG.NR_GUIA)
                  FROM DBAMV.ITEM_FAIXA_GUIA_CONVENIO IFG
                 WHERE IFG.CD_FAIXA_GUIA = FGC.CD_FAIXA_GUIA
                   AND IFG.NR_GUIA IS NOT NULL) AS QTD_UTILIZADA,
               O.RNK

          FROM DBAMV.FAIXA_GUIA_CONVENIO FGC

          INNER JOIN ORDEM O
          ON O.CD_FAIXA_GUIA = FGC.CD_FAIXA_GUIA

--        WHERE FGC.CD_FAIXA_GUIA = 700
)
 ORDER BY NR_FINAL DESC