  SELECT
    ta.DS_SENHA                                   AS "SENHA"
    ,FS.DS_FILA                                   AS "FILA"
    ,totem.DH_PROCESSO                            AS "DATA_HORA_SENHA"
    ,CLASCHAMADA.DH_PROCESSO                      AS "CHAMADA_TRIAGEM"
    ,CLASINI.DH_PROCESSO                          AS "INICIO_TRIAGEM"
    ,CLASINI.NM_USUARIO                           AS "TRIADOR"
    ,CLASFIM.DH_PROCESSO                          AS "FIM_TRIAGEM"
    ,CADINI.NM_LOCAL_ESTACAO                      AS "GUICHE"
    ,CADINI.DH_PROCESSO                           AS "CHAMADA"
    ,CADFIM.DH_PROCESSO                           AS "CONCLUSAO"

    -- Tempo de espera (assumindo tempo entre chegada e CHAMADA)
    ,ROUND((CADCHAMADA.DH_PROCESSO - TOTEM.DH_PROCESSO) * 24 * 60) AS "TEMPO_ESPERA_CHAMADA"

    -- Tempo de espera (assumindo tempo entre chegada e início)
    ,ROUND((CADINI.DH_PROCESSO - TOTEM.DH_PROCESSO) * 24 * 60) AS "TEMPO_ESPERA_INICIO"

    -- Duração do atendimento (conclusão - chamada)
    ,ROUND((CADFIM.DH_PROCESSO - CADINI.DH_PROCESSO) * 24 * 60) AS "DURACAO"

    ,CADINI.NM_USUARIO                            AS "ATENDENTE"

    ,CASE
        WHEN removido.CD_TRIAGEM_ATENDIMENTO IS NOT NULL THEN 'REMOVIDO'
        WHEN CADFIM.DH_PROCESSO IS NOT NULL THEN 'CONCLUIDO'
        ELSE 'EM ATENDIMENTO'
    END                                           AS "STATUS"

    ,MEDCHAMADA.DH_PROCESSO                       AS "CHAMADA_MED"
    ,MEDINI.DH_PROCESSO                           AS "MEDICO_INI"
    ,MEDFIM.DH_PROCESSO                           AS "MEDICO_FIM"



FROM
    DBAMV.TRIAGEM_ATENDIMENTO ta

JOIN FILA_SENHA FS
      ON FS.CD_FILA_SENHA = TA.CD_FILA_SENHA

-- Início (tipo 1 - senha emitida)
JOIN DBAMV.SACR_TEMPO_PROCESSO Totem
    ON totem.CD_TRIAGEM_ATENDIMENTO = ta.CD_TRIAGEM_ATENDIMENTO
   AND totem.CD_TIPO_TEMPO_PROCESSO = 1


-- chamada classificacao (tipo 10 - Classificacao / chamada)
LEFT JOIN DBAMV.SACR_TEMPO_PROCESSO CLASCHAMADA
    ON CLASCHAMADA.CD_TRIAGEM_ATENDIMENTO = ta.CD_TRIAGEM_ATENDIMENTO
   AND CLASCHAMADA.CD_TIPO_TEMPO_PROCESSO = 10


-- INICO classificacao (tipo 11 - Classificacao / INICIO)
LEFT JOIN DBAMV.SACR_TEMPO_PROCESSO CLASINI
    ON CLASINI.CD_TRIAGEM_ATENDIMENTO = ta.CD_TRIAGEM_ATENDIMENTO
   AND CLASINI.CD_TIPO_TEMPO_PROCESSO = 11

-- FINAL classificacao (tipo 12 - Classificacao / FINAL)
LEFT JOIN DBAMV.SACR_TEMPO_PROCESSO CLASFIM
    ON CLASFIM.CD_TRIAGEM_ATENDIMENTO = ta.CD_TRIAGEM_ATENDIMENTO
   AND CLASFIM.CD_TIPO_TEMPO_PROCESSO = 12

-- chamada Cadastro (tipo 20 - Cadastro / chamada)
LEFT JOIN DBAMV.SACR_TEMPO_PROCESSO CADCHAMADA
    ON CADCHAMADA.CD_TRIAGEM_ATENDIMENTO = ta.CD_TRIAGEM_ATENDIMENTO
   AND CADCHAMADA.CD_TIPO_TEMPO_PROCESSO = 20


-- INICO CADASTRO (tipo 21 - CADASTRO / INICIO)
LEFT JOIN DBAMV.SACR_TEMPO_PROCESSO CADINI
    ON CADINI.CD_TRIAGEM_ATENDIMENTO = ta.CD_TRIAGEM_ATENDIMENTO
   AND CADINI.CD_TIPO_TEMPO_PROCESSO = 21

-- FINAL CADASTRO (tipo 22 - CADASTRO / FINAL)
LEFT JOIN DBAMV.SACR_TEMPO_PROCESSO CADFIM
    ON CADFIM.CD_TRIAGEM_ATENDIMENTO = ta.CD_TRIAGEM_ATENDIMENTO
   AND CADFIM.CD_TIPO_TEMPO_PROCESSO = 22

-- chamada MEDICO(tipo 30 - MEDICO / chamada)
LEFT JOIN DBAMV.SACR_TEMPO_PROCESSO MEDCHAMADA
    ON MEDCHAMADA.CD_TRIAGEM_ATENDIMENTO = ta.CD_TRIAGEM_ATENDIMENTO
   AND MEDCHAMADA.CD_TIPO_TEMPO_PROCESSO = 30

-- INICO MEDICO (tipo 31 - MEDICO / INICIO)
LEFT JOIN DBAMV.SACR_TEMPO_PROCESSO MEDINI
    ON MEDINI.CD_TRIAGEM_ATENDIMENTO = ta.CD_TRIAGEM_ATENDIMENTO
   AND MEDINI.CD_TIPO_TEMPO_PROCESSO = 31

-- FINAL MEDICO (tipo 32 - MEDICO / FINAL)
LEFT JOIN DBAMV.SACR_TEMPO_PROCESSO MEDFIM
    ON MEDFIM.CD_TRIAGEM_ATENDIMENTO = ta.CD_TRIAGEM_ATENDIMENTO
   AND MEDFIM.CD_TIPO_TEMPO_PROCESSO = 32

-- Remoção (tipo 99)
LEFT JOIN DBAMV.SACR_TEMPO_PROCESSO removido
    ON removido.CD_TRIAGEM_ATENDIMENTO = ta.CD_TRIAGEM_ATENDIMENTO
   AND removido.CD_TIPO_TEMPO_PROCESSO = 99

WHERE
    totem.DH_PROCESSO BETWEEN (SYSDATE - 1) AND SYSDATE
    AND ta.CD_MULTI_EMPRESA IN (1)
    AND totem.CD_TRIAGEM_ATENDIMENTO IS NOT NULL

ORDER BY
    FS.DS_FILA,
    ta.DS_SENHA,
    STATUS



