SELECT
  --DADOS DAS MOVIMENTAÇÕES
  MOV_INT.CD_MOV_INT,

  MOV_INT.DT_MOV_INT DT_MOV_INT, --DATA DA MOVIMENTAÇÃO OU INTERNAÇÃO, USAR ESTE CAMPO NAS PESQUISAS POR POSSUI INDICE

  TRUNC(MOV_INT.DT_MOV_INT) + (MOV_INT.HR_MOV_INT - TRUNC(MOV_INT.HR_MOV_INT)) DH_MOV_INT,

  MOV_INT.DT_LIB_MOV DT_LIB_MOV, --DATA DA LIBERAÇÃO DA MOVIMENTAÇÃO, USAR ESTE CAMPO NAS PESQUISAS POR POSSUI INDICE

  TRUNC(MOV_INT.DT_LIB_MOV) + (MOV_INT.HR_LIB_MOV - TRUNC(MOV_INT.HR_LIB_MOV)) DH_LIB_MOV,

  MOV_INT.DS_MOTIVO, --CAMPO TEXTO

  CASE
     WHEN MOV_INT.TP_MOV = 'I' AND MOTIVO_TRANSF_LEITO.DS_MOTIVO_TRANSF_LEITO IS NULL THEN 'INTERNAÇÃO'
     WHEN MOV_INT.TP_MOV <> 'I' AND MOTIVO_TRANSF_LEITO.DS_MOTIVO_TRANSF_LEITO IS NULL THEN 'NÃO INFORMADO'
     ELSE MOTIVO_TRANSF_LEITO.DS_MOTIVO_TRANSF_LEITO
  END DS_MOTIVO_TRANSF_LEITO, --CAMPO NA TABELA DE MOTIVOS

  MOV_INT.TP_MOV,

  CASE MOV_INT.TP_MOV
    WHEN 'A' THEN 'ACOMPANHANTE'
    WHEN 'F' THEN 'INFECÇÃO'
    WHEN 'I' THEN 'INTERNAÇÃO'
    WHEN 'L' THEN 'LIMPEZA'
    WHEN 'M' THEN 'MANUTENÇÃO'
    WHEN 'O' THEN 'TRANSFERÊNCIA'
    WHEN 'R' THEN 'RESERVA'
    WHEN 'C' THEN 'INTERDITADO POR INFECÇÃO'
    WHEN 'T' THEN 'INTERDITADO POR ISOLAMENTO'
    WHEN 'E' THEN 'REFORMA'
    WHEN 'N' THEN 'INTERDIÇÃO'
    ELSE MOV_INT.TP_MOV
  END DS_TP_MOV,

  UNIDADE_ORIGEM.CD_UNID_INT CD_UNIDADE_ORIGEM,

  UNIDADE_ORIGEM.DS_UNID_INT DS_UNIDADE_ORIGEM,

  LEITO_ORIGEM.CD_LEITO CD_LEITO_ORIGEM,

  LEITO_ORIGEM.DS_LEITO DS_LEITO_ORIGEM,

  UNIDADE_DESTINO.CD_UNID_INT CD_UNIDADE_DESTINO,

  UNIDADE_DESTINO.DS_UNID_INT DS_UNIDADE_DESTINO,

  LEITO_DESTINO.CD_LEITO CD_LEITO_DESTINO,

  LEITO_DESTINO.DS_LEITO DS_LEITO_DESTINO,

  USUARIOS.NM_USUARIO,

  --DADOS DA INTERNACAO

  MULTI_EMPRESAS.CD_MULTI_EMPRESA CD_EMPRESA,

  MULTI_EMPRESAS.DS_MULTI_EMPRESA NM_EMPRESA,

  ATENDIME.CD_ATENDIMENTO CD_ATENDIMENTO,

  TRUNC(ATENDIME.DT_ATENDIMENTO) + (ATENDIME.HR_ATENDIMENTO - TRUNC(ATENDIME.HR_ATENDIMENTO)) DH_ATENDIMENTO,

  TRUNC(ATENDIME.DT_ALTA) + (ATENDIME.HR_ALTA - TRUNC(ATENDIME.HR_ALTA)) DH_ALTA,

  PACIENTE.CD_PACIENTE CD_PACIENTE,

  PACIENTE.NM_PACIENTE NM_PACIENTE,

  CONVENIO.CD_CONVENIO CD_CONVENIO,

  CONVENIO.NM_CONVENIO NM_CONVENIO,

  DECODE(CONVENIO.TP_CONVENIO,'C','CONVÊNIO','P','PARTICULAR','A','SUS','H','SUS',CONVENIO.TP_CONVENIO) DS_TIPO_CONVENIO,

  PRESTADOR.CD_PRESTADOR CD_PRESTADOR,

  PRESTADOR.NM_PRESTADOR NM_PRESTADOR,

  TIPO_INTERNACAO.CD_TIPO_INTERNACAO CD_TIPO_INTERNACAO,

  TIPO_INTERNACAO.DS_TIPO_INTERNACAO DS_TIPO_INTERNACAO,

  /*VERIFICA SE A MOVIMENTAÇÃO É INTERNADA NA UNIDADE, APENAS TROCA DE LEITO*/
  CASE
    WHEN UNIDADE_DESTINO.CD_UNID_INT <> UNIDADE_ORIGEM.CD_UNID_INT
         OR MOV_INT.TP_MOV = 'I'  THEN 1
    ELSE 0
  END SN_MOV_UNIDADE,

  /*VERIFICA SE HOUVE UMA ALTA EM 48H ANTERIOR, CARACTERIZANDO UM REINTERNACAO*/
  (SELECT MIN(TRUNC(T.DT_MOV_INT) + (T.HR_MOV_INT - TRUNC(T.HR_MOV_INT)))
     FROM DBAMV.MOV_INT T
          INNER JOIN DBAMV.LEITO L_DESTINO ON T.CD_LEITO = L_DESTINO.CD_LEITO
          LEFT JOIN  DBAMV.LEITO L_ORIGEM ON T.CD_LEITO_ANTERIOR = L_ORIGEM.CD_LEITO
    WHERE ATENDIME.CD_ATENDIMENTO = T.CD_ATENDIMENTO
          AND L_DESTINO.CD_UNID_INT <> L_ORIGEM.CD_UNID_INT --UNIDADES DIFERENTES
          AND LEITO_ORIGEM.CD_UNID_INT = L_DESTINO.CD_UNID_INT
          AND T.CD_MOV_INT > MOV_INT.CD_MOV_INT
          AND T.DT_MOV_INT - MOV_INT.DT_MOV_INT < 2
  ) DT_REINTERNACAO

FROM
  DBAMV.MOV_INT

  INNER JOIN DBAMV.LEITO LEITO_DESTINO ON MOV_INT.CD_LEITO = LEITO_DESTINO.CD_LEITO

  INNER JOIN DBAMV.UNID_INT UNIDADE_DESTINO ON LEITO_DESTINO.CD_UNID_INT = UNIDADE_DESTINO.CD_UNID_INT

  INNER JOIN DBAMV.SETOR ON UNIDADE_DESTINO.CD_SETOR = SETOR.CD_SETOR

  INNER JOIN DBAMV.MULTI_EMPRESAS ON SETOR.CD_MULTI_EMPRESA = MULTI_EMPRESAS.CD_MULTI_EMPRESA

  LEFT JOIN DBAMV.LEITO LEITO_ORIGEM ON MOV_INT.CD_LEITO_ANTERIOR =  LEITO_ORIGEM.CD_LEITO

  LEFT JOIN DBAMV.UNID_INT UNIDADE_ORIGEM ON LEITO_ORIGEM.CD_UNID_INT = UNIDADE_ORIGEM.CD_UNID_INT

  LEFT JOIN DBAMV.MOTIVO_TRANSF_LEITO ON MOV_INT.CD_MOTIVO_TRANSF_LEITO = MOTIVO_TRANSF_LEITO.CD_MOTIVO_TRANSF_LEITO

  LEFT JOIN DBAMV.ATENDIME ON MOV_INT.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO
                              AND ATENDIME.TP_ATENDIMENTO = 'I' /*SOMENTE INTERNAÇÃO*/

  LEFT JOIN DBAMV.PACIENTE ON ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE

  LEFT JOIN DBAMV.CONVENIO ON ATENDIME.CD_CONVENIO = CONVENIO.CD_CONVENIO

  LEFT JOIN DBAMV.TIPO_INTERNACAO ON ATENDIME.CD_TIPO_INTERNACAO = TIPO_INTERNACAO.CD_TIPO_INTERNACAO

  LEFT JOIN DBAMV.PRESTADOR ON ATENDIME.CD_PRESTADOR = PRESTADOR.CD_PRESTADOR

  LEFT JOIN DBASGU.USUARIOS ON MOV_INT.NM_USUARIO = USUARIOS.CD_USUARIO

WHERE
  MOV_INT.DT_MOV_INT >= TRUNC(ADD_MONTHS(NVL(:VC_DT_PADRAO,SYSDATE),-36),'MONTH') /*FIXO ÚLTIMOS 3 ANOS*/