SELECT --ATENDIME.CD_ATENDIMENTO ATENDIMENTO,
      -- PACIENTE.NM_PACIENTE PACIENTE,
      -- PRE_MED.CD_PRE_MED,
       ITPRE_MED.CD_TIP_PRESC,
       TIP_PRESC.DS_TIP_PRESC,
      -- PRE_MED.CD_SETOR,
       SETOR.NM_SETOR SETOR,
       Count (DISTINCT PRE_MED.CD_PRE_MED) QTDPRESC
     --  Count (*) QTDITENS
      -- ITPRE_MED.CD_TIP_ESQ,
      -- TIP_ESQ.DS_TIP_ESQ,
      --(SELECT Count (CD_PRE_MED) FROM PRE_MED WHERE ITPRE_MED.CD_PRE_MED = PRE_MED.CD_PRE_MED)

FROM ATENDIME,
     ITPRE_MED,
     PRE_MED,
     PACIENTE,
     SETOR,
     TIP_PRESC,
     TIP_ESQ

WHERE ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
      AND ITPRE_MED.CD_PRE_MED = PRE_MED.CD_PRE_MED
      AND PRE_MED.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO
      AND PRE_MED.CD_SETOR  =  SETOR.CD_SETOR
      AND ITPRE_MED.CD_TIP_PRESC =  TIP_PRESC.CD_TIP_PRESC
      AND ITPRE_MED.CD_TIP_ESQ = TIP_ESQ.CD_TIP_ESQ
      AND SETOR.CD_MULTI_EMPRESA = '4'
    --  AND ITPRE_MED.CD_TIP_ESQ IN('MED','MNP','MPR','ONC','IAF')
      AND Trunc (PRE_MED.DT_PRE_MED) BETWEEN To_Date('01/06/2018','DD/MM/YYYY') AND To_Date('12/06/2018','DD/MM/YYYY')
      -- AND ATENDIME.CD_ATENDIMENTO = 1550658
      AND ITpre_med.CD_TIP_PRESC = 48348
GROUP BY --ATENDIME.CD_ATENDIMENTO,
      -- PACIENTE.NM_PACIENTE,
     --  PRE_MED.CD_PRE_MED,
      ITPRE_MED.CD_TIP_PRESC,
      TIP_PRESC.DS_TIP_PRESC,
     --  PRE_MED.CD_SETOR,
       SETOR.NM_SETOR
     --  ITPRE_MED.CD_TIP_ESQ,
     --  TIP_ESQ.DS_TIP_ESQ

ORDER BY 1  