-- R_EST_INTER_UNID 1

SELECT * FROM (
SELECT UNID_INT.CD_UNID_INT   CD_UNIDADE
             ,ATENDIME.CD_CONVENIO
             ,CONVENIO.NM_CONVENIO
             ,COUNT(*)  QUANT_CONV
FROM   DBAMV.ATENDIME
            ,DBAMV.CONVENIO
            ,DBAMV.LEITO
            ,DBAMV.UNID_INT
            ,DBAMV.MOV_INT
WHERE  ATENDIME.TP_ATENDIMENTO  IN  ('I', 'H')
AND        ATENDIME.CD_ATENDIMENTO_PAI IS NULL
AND        TRUNC(MOV_INT.DT_MOV_INT)  BETWEEN   $P{P_DT_INICIO}    AND   $P{P_DT_FINAL}
AND        ATENDIME.CD_CONVENIO  =  CONVENIO.CD_CONVENIO
AND        MOV_INT.CD_LEITO  =  LEITO.CD_LEITO
AND        LEITO.CD_UNID_INT  =  UNID_INT.CD_UNID_INT
AND        ATENDIME.CD_ATENDIMENTO = MOV_INT.CD_ATENDIMENTO
AND        MOV_INT.TP_MOV = 'I'
and ATENDIME.CD_MULTI_EMPRESA = $P{P_CD_MULTI_EMPRESA}
$P!{CF_UNID_INT}
$P!{CF_COND_CONV}
GROUP BY   UNID_INT.CD_UNID_INT
                     ,ATENDIME.CD_CONVENIO
                    ,CONVENIO.NM_CONVENIO
ORDER BY   QUANT_CONV  DESC
)
WHERE CD_UNIDADE = $P{CD_UNID_INT}