-- R_ORD_COM
SELECT ORD_COM.CD_ORD_COM,
       ORD_COM.DT_ORD_COM,
       FORNECEDOR.NM_FORNECEDOR,
       ORD_COM.VL_TOTAL,
       ITEM_ORD_COM.CD_PRODUTO,
       PRODUTO.DS_PRODUTO,
       ITEM_ORD_COM.QT_COMPRADA,
       ITEM_ORD_COM.VL_UNITARIO,
       (ITEM_ORD_COM.QT_COMPRADA * ITEM_ORD_COM.VL_UNITARIO) AS VL_TOTAL_ITEM
  FROM DBAMV.ORD_COM,
       DBAMV.FORNECEDOR,
       DBAMV.ITEM_ORD_COM,
       DBAMV.PRODUTO
 WHERE ORD_COM.CD_FORNECEDOR = FORNECEDOR.CD_FORNECEDOR
   AND ORD_COM.CD_ORD_COM = ITEM_ORD_COM.CD_ORD_COM
   AND ITEM_ORD_COM.CD_PRODUTO = PRODUTO.CD_PRODUTO
   AND ORD_COM.CD_MULTI_EMPRESA = 1
   AND TRUNC(ORD_COM.DT_ORD_COM) BETWEEN TRUNC(SYSDATE) AND TRUNC(SYSDATE)
 ORDER BY ORD_COM.CD_ORD_COM