-- tabelas dos docs eletronicos
SELECT ROW_NUMBER() OVER(PARTITION BY DC.CD_ATENDIMENTO ORDER BY DC.CD_DOCUMENTO_CLINICO DESC) NR_LINHA,
               DC.CD_DOCUMENTO_CLINICO,
               DC.DH_CRIACAO,
               DC.CD_ATENDIMENTO,
               ATE.TP_ATENDIMENTO,
               DC.CD_PACIENTE,
               P.NM_PACIENTE,
               TO_CHAR(P.DT_NASCIMENTO, 'DD/MM/YYYY') DT_NASCIMENTO,
               ATE.CD_CID,
               C.DS_CID,
               ATE.CD_CONVENIO,
               CV.NM_CONVENIO,
               Decode(EC.DS_IDENTIFICADOR,'SN_1_PERMANENCIA_CVC_SIM_1','Sim','SN_1_PERMANENCIA_CVC_NAO_1','Não','SN_1_PERMANENCIA_CVC_NSA_1','Não se Aplica') DS_JUSTIFICA,
               FNC_MV_RECUPERA_DATA_HORA(ATE.DT_ATENDIMENTO,ATE.HR_ATENDIMENTO) DT_ATENDIMENTO,
               DBAMV.FNC_LEITO_ATENDIMENTO(DC.CD_ATENDIMENTO, DC.DH_CRIACAO) CD_LEITO,
               L.DS_RESUMO,
               DBMS_LOB.SUBSTR (ERC.LO_VALOR , 4000, 1 )
          FROM DBAMV.PW_DOCUMENTO_CLINICO DC JOIN DBAMV.PW_EDITOR_CLINICO PEC ON DC.CD_DOCUMENTO_CLINICO = PEC.CD_DOCUMENTO_CLINICO
                                             JOIN DBAMV.EDITOR_REGISTRO_CAMPO ERC ON PEC.CD_EDITOR_REGISTRO = ERC.CD_REGISTRO
                                             JOIN DBAMV.EDITOR_CAMPO EC ON ERC.CD_CAMPO = EC.CD_CAMPO
                                             JOIN DBAMV.ATENDIME ATE ON DC.CD_ATENDIMENTO = ATE.CD_ATENDIMENTO
                                             JOIN DBAMV.PACIENTE P ON ATE.CD_PACIENTE = P.CD_PACIENTE
                                             JOIN DBAMV.CONVENIO CV ON ATE.CD_CONVENIO = CV.CD_CONVENIO
                                             LEFT JOIN DBAMV.CID C ON ATE.CD_CID = C.CD_CID
                                             JOIN DBAMV.LEITO L ON DBAMV.FNC_LEITO_ATENDIMENTO(DC.CD_ATENDIMENTO, DC.DH_CRIACAO) = L.CD_LEITO
                                             JOIN DBAMV.UNID_INT UI ON L.CD_UNID_INT = UI.CD_UNID_INT
         WHERE PEC.CD_DOCUMENTO = 795
           AND DC.TP_STATUS = 'FECHADO'
           AND ATE.TP_ATENDIMENTO = 'I'
           AND EC.DS_IDENTIFICADOR IN('SN_1_PERMANENCIA_CVC_SIM_1')
           AND DBMS_LOB.SUBSTR (ERC.LO_VALOR , 4000, 1 ) = 'true'
           AND DC.DH_FECHAMENTO BETWEEN TO_DATE(  /$gDataInicio$/'01/09/2025'  , 'DD/MM/YYYY') AND TO_DATE(  /$gDataFim$/'30/09/2025'   , 'DD/MM/YYYY') + 0.99999