-- TRANSFERÊNCIA DE LEITOS

SELECT
    STL.CD_ATENDIMENTO,
    P.NM_PACIENTE,
    TIP_ACOM.DS_TIP_ACOM,
    STL.HR_SOLIC_TRANSF,
    STL.DH_SOLICITACAO,

    (SELECT MOV_INT.HR_MOV_INT
     FROM MOV_INT
     WHERE MOV_INT.CD_ATENDIMENTO = STL.CD_ATENDIMENTO
     AND MOV_INT.SN_RESERVA = 'S'
     FETCH FIRST ROW ONLY) AS HR_MOV_INT_APROVACAO,

    (SELECT MOV_INT.HR_MOV_INT
     FROM MOV_INT
     WHERE MOV_INT.CD_ATENDIMENTO = STL.CD_ATENDIMENTO
     AND MOV_INT.SN_RESERVA = 'N'
     AND TRUNC(MOV_INT.HR_MOV_INT) = TRUNC(STL.DH_SOLICITACAO) -- Verifica se a data é a mesma
     ORDER BY MOV_INT.HR_MOV_INT DESC
     FETCH FIRST ROW ONLY) AS HR_MOV_INT_CONFIRMACAO,

    STL.CD_USUARIO_SOLICITACAO,
    DECODE(STL.TP_SITUACAO, 'R', 'REALIZADA', 'A', 'ATENDIDA', 'S', 'SOLICITADA', 'C', 'CANCELADA') AS TP_SITUACAO

FROM
    SOLIC_TRANSFERENCIA_LEITO STL
    JOIN ATENDIME A ON STL.CD_ATENDIMENTO = A.CD_ATENDIMENTO
    JOIN PACIENTE P ON P.CD_PACIENTE = A.CD_PACIENTE
    JOIN TIP_ACOM ON STL.CD_TIP_ACOM = TIP_ACOM.CD_TIP_ACOM

ORDER BY
    STL.CD_SOLIC_TRANSFERENCIA_LEITO DESC