SELECT
ATENDIME.CD_ATENDIMENTO,
PACIENTE.NM_PACIENTE,
To_Char(PACIENTE.DT_NASCIMENTO, 'DD/MM/YYYY') DT_NASCIMENTO,
SOLSAI_PRO.CD_SOLSAI_PRO,
LEITO.DS_LEITO,
SETOR.NM_SETOR,
PRODUTO.DS_PRODUTO,
ITPRE_MED.CD_FOR_APL,
TIP_FRE.DS_TIP_FRE,
ITSOLSAI_PRO.QT_SOLICITADO,
PRE_MED.HR_PRE_MED

FROM
ATENDIME,
PACIENTE,
PRE_MED,
ITPRE_MED,
LEITO,
SETOR,
PRODUTO,
TIP_FRE,
SOLSAI_PRO,
ITSOLSAI_PRO

WHERE ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
  AND ATENDIME.CD_ATENDIMENTO = PRE_MED.CD_ATENDIMENTO
  AND ATENDIME.CD_ATENDIMENTO = SOLSAI_PRO.CD_ATENDIMENTO AND PRE_MED.CD_PRE_MED = SOLSAI_PRO.CD_PRE_MED
  AND SOLSAI_PRO.CD_SOLSAI_PRO = ITSOLSAI_PRO.CD_SOLSAI_PRO
  AND ITSOLSAI_PRO.CD_PRODUTO = PRODUTO.CD_PRODUTO
  AND PRE_MED.CD_PRE_MED = ITPRE_MED.CD_PRE_MED
  AND ITPRE_MED.CD_TIP_FRE = TIP_FRE.CD_TIP_FRE
  AND SOLSAI_PRO.CD_SETOR = SETOR.CD_SETOR
  AND ATENDIME.CD_LEITO = LEITO.CD_LEITO

  AND SOLSAI_PRO.CD_SOLSAI_PRO = 2387177