
  CREATE TABLE "DBAMV"."REPASSE_IMAGEM_SW"
   (	"TUSS" VARCHAR2(10),
	"CONVENIO" VARCHAR2(10),
	"VL_TOTAL" NUMBER(14,4)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MV2000_D" ;

   REFERENCES "DBAMV"."REPASSE_IMAGEM_SW" ("TUSS") ENABLE,
	 CONSTRAINT "REPASSE_IMAGEM_SW_PK" PRIMARY KEY ("CONVENIO")

   CONSTRAINT "CNT_CONFIGURACAO_1_UK" UNIQUE ("TUSS", "CONVENIO")





