SELECT
TO_CHAR(AVISO_CIRURGIA.DT_REALIZACAO, 'DD/MM/YYYY') DT_REALIZACAO,
ATENDIME.CD_ATENDIMENTO,
PACIENTE.NM_PACIENTE,
TRUNC(MONTHS_BETWEEN(SYSDATE, PACIENTE.DT_NASCIMENTO) / 12) AS IDADE,
PACIENTE.NR_CPF,
PACIENTE.NR_FONE,
'(' || PACIENTE.NR_DDD_CELULAR || ') ' || PACIENTE.NR_CELULAR AS CELULAR,
'(' || PACIENTE.NR_DDD_FONE    || ') ' || PACIENTE.NR_FONE    AS FONE,
CIRURGIA.DS_CIRURGIA,
ESPECIALID.DS_ESPECIALID

FROM
ATENDIME,
PACIENTE,
AVISO_CIRURGIA,
CIRURGIA_AVISO,
CIRURGIA,
ESPECIALID

WHERE ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
  AND AVISO_CIRURGIA.CD_AVISO_CIRURGIA = CIRURGIA_AVISO.CD_AVISO_CIRURGIA
  AND CIRURGIA_AVISO.CD_CIRURGIA = CIRURGIA.CD_CIRURGIA
  AND AVISO_CIRURGIA.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO
  AND CIRURGIA_AVISO.CD_ESPECIALID = ESPECIALID.CD_ESPECIALID (+)

  AND AVISO_CIRURGIA.TP_SITUACAO = 'R'
  AND {V_VAR}
  AND TO_DATE(AVISO_CIRURGIA.DT_REALIZACAO, 'DD/MM/YYYY') BETWEEN To_Date(@PDATA_INICIAL, 'DD/MM/YYYY') AND TO_DATE(@PDATA_FINAL, 'DD/MM/YYYY')

ORDER BY DT_REALIZACAO, DS_ESPECIALID