WITH teste AS (
    SELECT
        ATENDIME.CD_ATENDIMENTO,
        PACIENTE.NM_PACIENTE,
        SETOR.CD_SETOR,
        TRUNC(MONTHS_BETWEEN(SYSDATE, PACIENTE.DT_NASCIMENTO) / 12) AS IDADE,
        TO_CHAR(PACIENTE.DT_NASCIMENTO, 'DD/MM/YYYY') DT_NASCIMENTO,
        PRODUTO.DS_PRODUTO AS PRODUTO,
        ITPRE_MED.QT_ITPRE_MED,
        ITSOLSAI_PRO.QT_ATENDIDA AS QTD
    FROM
        SOLSAI_PRO,
        ITSOLSAI_PRO,
        PRODUTO,
        ATENDIME,
        PACIENTE,
        PRE_MED,
        ITPRE_MED,
        SETOR
    WHERE
        SOLSAI_PRO.CD_SOLSAI_PRO = ITSOLSAI_PRO.CD_SOLSAI_PRO
        AND ITSOLSAI_PRO.CD_PRODUTO = PRODUTO.CD_PRODUTO
        AND ATENDIME.CD_ATENDIMENTO = SOLSAI_PRO.CD_ATENDIMENTO
        AND ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
        AND ITSOLSAI_PRO.CD_ITPRE_MED = ITPRE_MED.CD_ITPRE_MED
        AND SETOR.CD_SETOR = PRE_MED.CD_SETOR
        AND PRE_MED.CD_PRE_MED = SOLSAI_PRO.CD_PRE_MED
        AND SOLSAI_PRO.CD_SOLSAI_PRO = 2387177

),

teste2 AS (
    SELECT
        ATENDIME.CD_ATENDIMENTO,
        PRODUTO.DS_PRODUTO AS COMPONENTE,
        SUM(ITSOLSAI_PRO.QT_ATENDIDA) AS QTD
    FROM
        SOLSAI_PRO,
        ITSOLSAI_PRO,
        PRODUTO,
        ATENDIME
    WHERE
        SOLSAI_PRO.CD_SOLSAI_PRO = ITSOLSAI_PRO.CD_SOLSAI_PRO
        AND ITSOLSAI_PRO.CD_PRODUTO = PRODUTO.CD_PRODUTO
        AND ITSOLSAI_PRO.QT_ATENDIDA > 0
        AND ATENDIME.CD_ATENDIMENTO = SOLSAI_PRO.CD_ATENDIMENTO
        AND EXISTS (
            SELECT 1
              FROM CITPRE_MED C
             WHERE C.CD_ITPRE_MED = ITSOLSAI_PRO.CD_ITPRE_MED
               AND C.CD_TIP_PRESC = ITSOLSAI_PRO.CD_TIP_PRESC
               AND C.CD_PRODUTO = PRODUTO.CD_PRODUTO
               AND PRODUTO.CD_ESPECIE NOT IN (2)
        )
    GROUP BY ATENDIME.CD_ATENDIMENTO, PRODUTO.DS_PRODUTO
)

SELECT
    t.CD_ATENDIMENTO,
    t.CD_SETOR,
    t.PRODUTO,
    NVL(LISTAGG(t2.COMPONENTE, ', ') WITHIN GROUP (ORDER BY t2.COMPONENTE), 'SEM COMPONENTE') AS COMPONENTES,
    t.NM_PACIENTE,
    t.IDADE,
    t.DT_NASCIMENTO,
    t.QTD
FROM
    teste t
LEFT JOIN
    teste2 t2
    ON t.CD_ATENDIMENTO = t2.CD_ATENDIMENTO
GROUP BY
    t.CD_ATENDIMENTO,
    t.CD_SETOR,
    t.PRODUTO,
    t.NM_PACIENTE,
    t.IDADE,
    t.DT_NASCIMENTO,
    t.QTD
