SELECT
ATENDIME.CD_ATENDIMENTO,
PACIENTE.NM_PACIENTE,
SETOR.NM_SETOR,
SOLSAI_PRO.CD_SOLSAI_PRO,
PRODUTO.CD_PRODUTO,
LEITO.DS_LEITO,
round(Decode ( PRE_MED.CD_PRE_MED, NULL , 0, DECODE(nvl(dbamv.pkg_mv2000.le_configuracao('PSIH', 'SN_DOSE_PRESCRICAO'),'N'), 'N', DBAMV.FNC_PSIH_RETORNA_DOSE(ATENDIME.CD_ATENDIMENTO,ITPRE_MED.CD_PRE_MED,PRODUTO.CD_PRODUTO,SOLSAI_PRO.CD_SOLSAI_PRO ), DBAMV.FNC_PSIH_RETORNA_DOSE(ATENDIME.CD_ATENDIMENTO,ITPRE_MED.CD_PRE_MED,PRODUTO.CD_PRODUTO,ITPRE_MED.CD_ITPRE_MED ) ) ),3) NR_DOSE,
TRUNC(MONTHS_BETWEEN(SYSDATE, PACIENTE.DT_NASCIMENTO) / 12) AS IDADE,
TO_CHAR(PACIENTE.DT_NASCIMENTO, 'DD/MM/YYYY') DT_NASCIMENTO,
PRODUTO.DS_PRODUTO AS PRODUTO,
TIP_FRE.DS_TIP_FRE,
FOR_APL.DS_FOR_APL || ' (' || FOR_APL.CD_FOR_APL || ')' FORMA_APL,
ITPRE_MED.QT_ITPRE_MED

FROM
SOLSAI_PRO,
ITSOLSAI_PRO,
PRODUTO,
ATENDIME,
PACIENTE,
PRE_MED,
ITPRE_MED,
SETOR,
LEITO,
TIP_FRE,
FOR_APL

WHERE SOLSAI_PRO.CD_SOLSAI_PRO = ITSOLSAI_PRO.CD_SOLSAI_PRO
  AND ITSOLSAI_PRO.CD_PRODUTO = PRODUTO.CD_PRODUTO
  AND ATENDIME.CD_ATENDIMENTO = SOLSAI_PRO.CD_ATENDIMENTO
  AND ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
  AND ITSOLSAI_PRO.CD_ITPRE_MED = ITPRE_MED.CD_ITPRE_MED
  AND SETOR.CD_SETOR = PRE_MED.CD_SETOR
  AND PRE_MED.CD_PRE_MED = SOLSAI_PRO.CD_PRE_MED
  AND ITPRE_MED.CD_FOR_APL = FOR_APL.CD_FOR_APL
  AND ITPRE_MED.CD_TIP_FRE = TIP_FRE.CD_TIP_FRE
  AND ATENDIME.CD_LEITO = LEITO.CD_LEITO
  AND SOLSAI_PRO.CD_SOLSAI_PRO = 2384359-- {V_SOLICITACAO}

