select * from (
WITH produtos AS (
  SELECT
    ATENDIME.CD_ATENDIMENTO,
    PACIENTE.NM_PACIENTE,
    SETOR.CD_SETOR,
    TRUNC(MONTHS_BETWEEN(SYSDATE, PACIENTE.DT_NASCIMENTO) / 12) AS IDADE,
    TO_CHAR(PACIENTE.DT_NASCIMENTO, 'DD/MM/YYYY') DT_NASCIMENTO,
    PRODUTO.DS_PRODUTO AS DS_PRODUTO,
    ITPRE_MED.QT_ITPRE_MED,
    ITSOLSAI_PRO.QT_ATENDIDA AS QTD,
    ITSOLSAI_PRO.CD_ITPRE_MED,
    ITSOLSAI_PRO.CD_TIP_PRESC,
    UNI_PRO.DS_UNIDADE
  FROM
    SOLSAI_PRO
    JOIN ITSOLSAI_PRO ON SOLSAI_PRO.CD_SOLSAI_PRO = ITSOLSAI_PRO.CD_SOLSAI_PRO
    JOIN PRODUTO ON ITSOLSAI_PRO.CD_PRODUTO = PRODUTO.CD_PRODUTO
    JOIN ATENDIME ON ATENDIME.CD_ATENDIMENTO = SOLSAI_PRO.CD_ATENDIMENTO
    JOIN PACIENTE ON ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
    JOIN PRE_MED ON PRE_MED.CD_PRE_MED = SOLSAI_PRO.CD_PRE_MED
    JOIN ITPRE_MED ON ITSOLSAI_PRO.CD_ITPRE_MED = ITPRE_MED.CD_ITPRE_MED
    JOIN SETOR ON SETOR.CD_SETOR = PRE_MED.CD_SETOR
    JOIN UNI_PRO ON UNI_PRO.CD_PRODUTO = ITSOLSAI_PRO.CD_PRODUTO
                 AND UNI_PRO.CD_UNI_PRO = ITSOLSAI_PRO.CD_UNI_PRO
  WHERE ITSOLSAI_PRO.QT_ATENDIDA <> 0

   and NOT EXISTS (
      SELECT 1
      FROM CITPRE_MED C
      WHERE C.CD_ITPRE_MED = ITSOLSAI_PRO.CD_ITPRE_MED
        AND C.CD_TIP_PRESC = ITSOLSAI_PRO.CD_TIP_PRESC
    )
   -- AND ATENDIME.CD_ATENDIMENTO = {V_SOLICITACAO}
),

componentes AS (
  SELECT
    C.CD_ITPRE_MED,
    C.CD_TIP_PRESC,
    P.DS_PRODUTO AS DS_COMPONENTE,
    SUM(ITSOLSAI_PRO.QT_ATENDIDA) AS QTD_COMPONENTE
  FROM
    CITPRE_MED C
    JOIN PRODUTO P ON P.CD_PRODUTO = C.CD_PRODUTO
    JOIN ITSOLSAI_PRO ON C.CD_ITPRE_MED = ITSOLSAI_PRO.CD_ITPRE_MED
                      AND C.CD_TIP_PRESC = ITSOLSAI_PRO.CD_TIP_PRESC
    JOIN SOLSAI_PRO ON SOLSAI_PRO.CD_SOLSAI_PRO = ITSOLSAI_PRO.CD_SOLSAI_PRO
  WHERE
    ITSOLSAI_PRO.QT_ATENDIDA > 0
    AND P.CD_ESPECIE NOT IN (2)
  GROUP BY
    C.CD_ITPRE_MED,
    C.CD_TIP_PRESC,
    P.DS_PRODUTO
)

SELECT
  p.CD_ATENDIMENTO,
  p.CD_SETOR,
  p.NM_PACIENTE,
  p.DT_NASCIMENTO,
  p.IDADE,
  p.DS_PRODUTO || ', QTD: ' || p.QTD || ', UNID: ' || p.DS_UNIDADE  AS PRODUTO_PRESCRITO,
  p.QT_ITPRE_MED,
  p.QTD AS QTD_PRODUTO,
  p.DS_UNIDADE,
  c.DS_COMPONENTE || ', QTD: ' || c.QTD_COMPONENTE AS COMPONENTE_PRESCRITO,
  c.QTD_COMPONENTE
FROM
  produtos p
LEFT JOIN
  componentes c
  ON c.CD_ITPRE_MED = p.CD_ITPRE_MED
 )--- where componente_prescrito not like ('SORO%100%')
 --AND
where componente_prescrito not like ('%AGUA%DEST%')

 UNION

 SELECT CD_ATENDIMENTO,CD_SETOR, NM_PACIENTE, DT_NASCIMENTO,IDADE, COMPONENTE_PRESCRITO,QTD_COMPONENTE,QTD_COMPONENTE,DS_UNIDADE,NULL,QTD_COMPONENTE  FROM (
 WITH produtos AS (
  SELECT
    ATENDIME.CD_ATENDIMENTO,
    PACIENTE.NM_PACIENTE,
    SETOR.CD_SETOR,
    TRUNC(MONTHS_BETWEEN(SYSDATE, PACIENTE.DT_NASCIMENTO) / 12) AS IDADE,
    TO_CHAR(PACIENTE.DT_NASCIMENTO, 'DD/MM/YYYY') DT_NASCIMENTO,
   PRODUTO.DS_PRODUTO AS DS_PRODUTO,
    ITPRE_MED.QT_ITPRE_MED,
    ITSOLSAI_PRO.QT_ATENDIDA AS QTD,
    ITSOLSAI_PRO.CD_ITPRE_MED,
    ITSOLSAI_PRO.CD_TIP_PRESC,
    UNI_PRO.DS_UNIDADE
  FROM
    SOLSAI_PRO
    JOIN ITSOLSAI_PRO ON SOLSAI_PRO.CD_SOLSAI_PRO = ITSOLSAI_PRO.CD_SOLSAI_PRO
    JOIN PRODUTO ON ITSOLSAI_PRO.CD_PRODUTO = PRODUTO.CD_PRODUTO
    JOIN ATENDIME ON ATENDIME.CD_ATENDIMENTO = SOLSAI_PRO.CD_ATENDIMENTO
    JOIN PACIENTE ON ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
    JOIN PRE_MED ON PRE_MED.CD_PRE_MED = SOLSAI_PRO.CD_PRE_MED
    JOIN ITPRE_MED ON ITSOLSAI_PRO.CD_ITPRE_MED = ITPRE_MED.CD_ITPRE_MED
    JOIN SETOR ON SETOR.CD_SETOR = PRE_MED.CD_SETOR
    JOIN UNI_PRO ON UNI_PRO.CD_PRODUTO = ITSOLSAI_PRO.CD_PRODUTO
                 AND UNI_PRO.CD_UNI_PRO = ITSOLSAI_PRO.CD_UNI_PRO
  WHERE ITSOLSAI_PRO.QT_ATENDIDA <> 0

   and NOT EXISTS (
      SELECT 1
      FROM CITPRE_MED C
      WHERE C.CD_ITPRE_MED = ITSOLSAI_PRO.CD_ITPRE_MED
        AND C.CD_TIP_PRESC = ITSOLSAI_PRO.CD_TIP_PRESC
    )
    --AND ATENDIME.CD_ATENDIMENTO = {V_SOLICITACAO}
),

componentes AS (
  SELECT
    C.CD_ITPRE_MED,
    C.CD_TIP_PRESC,
    P.DS_PRODUTO AS DS_COMPONENTE,
    SUM(ITSOLSAI_PRO.QT_ATENDIDA) AS QTD_COMPONENTE
  FROM
    CITPRE_MED C
    JOIN PRODUTO P ON P.CD_PRODUTO = C.CD_PRODUTO
    JOIN ITSOLSAI_PRO ON C.CD_ITPRE_MED = ITSOLSAI_PRO.CD_ITPRE_MED
                      AND C.CD_TIP_PRESC = ITSOLSAI_PRO.CD_TIP_PRESC
    JOIN SOLSAI_PRO ON SOLSAI_PRO.CD_SOLSAI_PRO = ITSOLSAI_PRO.CD_SOLSAI_PRO
  WHERE
    ITSOLSAI_PRO.QT_ATENDIDA > 0
    AND P.CD_ESPECIE NOT IN (2)
  GROUP BY
    C.CD_ITPRE_MED,
    C.CD_TIP_PRESC,
    P.DS_PRODUTO
)

SELECT
  p.CD_ATENDIMENTO,
  p.CD_SETOR,
  p.NM_PACIENTE,
  p.DT_NASCIMENTO,
  p.IDADE,
  p.DS_PRODUTO || ', QTD: ' || p.QTD || ', UNID: ' || p.DS_UNIDADE  AS PRODUTO_PRESCRITO,
  p.QT_ITPRE_MED,
  p.QTD AS QTD_PRODUTO,
  p.DS_UNIDADE,
  c.DS_COMPONENTE || ', QTD: ' || c.QTD_COMPONENTE AS COMPONENTE_PRESCRITO,
  c.QTD_COMPONENTE
FROM
  produtos p
LEFT JOIN
  componentes c
  ON c.CD_ITPRE_MED = p.CD_ITPRE_MED)
   where componente_prescrito  like ('SORO%100%')
     AND PRODUTO_PRESCRITO NOT LIKE ('SORO%100%')