SELECT * FROM (
WITH PRODUTOS AS (
  SELECT
    ATENDIME.CD_ATENDIMENTO,
    PACIENTE.NM_PACIENTE,
    SETOR.CD_SETOR,
    SOLSAI_PRO.CD_SOLSAI_PRO,
    TRUNC(MONTHS_BETWEEN(SYSDATE, PACIENTE.DT_NASCIMENTO) / 12) AS IDADE,
    TO_CHAR(PACIENTE.DT_NASCIMENTO, 'DD/MM/YYYY') DT_NASCIMENTO,
    PRODUTO.DS_PRODUTO AS DS_PRODUTO,
    ITPRE_MED.QT_ITPRE_MED,
    ITSOLSAI_PRO.QT_ATENDIDA AS QTD,
    ITSOLSAI_PRO.CD_ITPRE_MED,
    ITSOLSAI_PRO.CD_TIP_PRESC,
    UNI_PRO.DS_UNIDADE,
    ITPRE_MED.CD_FOR_APL,
    TIP_FRE.DS_TIP_FRE,
    LEITO.DS_LEITO,
    SETOR.NM_SETOR,
    PACIENTE.NM_MAE,
    ITPRE_MED.DS_ITPRE_MED
  FROM
    SOLSAI_PRO
    JOIN ITSOLSAI_PRO ON SOLSAI_PRO.CD_SOLSAI_PRO = ITSOLSAI_PRO.CD_SOLSAI_PRO
    JOIN PRODUTO ON ITSOLSAI_PRO.CD_PRODUTO = PRODUTO.CD_PRODUTO
    JOIN ATENDIME ON ATENDIME.CD_ATENDIMENTO = SOLSAI_PRO.CD_ATENDIMENTO
    JOIN PACIENTE ON ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
    JOIN PRE_MED ON PRE_MED.CD_PRE_MED = SOLSAI_PRO.CD_PRE_MED
    JOIN ITPRE_MED ON ITSOLSAI_PRO.CD_ITPRE_MED = ITPRE_MED.CD_ITPRE_MED
    JOIN TIP_FRE ON ITPRE_MED.CD_TIP_FRE = TIP_FRE.CD_TIP_FRE
    JOIN LEITO ON LEITO.CD_LEITO = ATENDIME.CD_LEITO
    JOIN SETOR ON SETOR.CD_SETOR = PRE_MED.CD_SETOR
    JOIN UNI_PRO ON UNI_PRO.CD_PRODUTO = ITSOLSAI_PRO.CD_PRODUTO
                 AND UNI_PRO.CD_UNI_PRO = ITSOLSAI_PRO.CD_UNI_PRO
  WHERE NOT EXISTS (
      SELECT 1
      FROM CITPRE_MED C
      WHERE C.CD_ITPRE_MED = ITSOLSAI_PRO.CD_ITPRE_MED
        AND C.CD_TIP_PRESC = ITSOLSAI_PRO.CD_TIP_PRESC
    )
    AND SOLSAI_PRO.CD_SOLSAI_PRO = {V_SOLICITACAO}
),

COMPONENTES AS (
  SELECT
    C.CD_ITPRE_MED,
    C.CD_TIP_PRESC,
    P.DS_PRODUTO AS DS_COMPONENTE,
    SUM(ITSOLSAI_PRO.QT_ATENDIDA) AS QTD_COMPONENTE
  FROM
    CITPRE_MED C
    JOIN PRODUTO P ON P.CD_PRODUTO = C.CD_PRODUTO
    JOIN ITSOLSAI_PRO ON C.CD_ITPRE_MED = ITSOLSAI_PRO.CD_ITPRE_MED
                      AND C.CD_TIP_PRESC = ITSOLSAI_PRO.CD_TIP_PRESC
    JOIN SOLSAI_PRO ON SOLSAI_PRO.CD_SOLSAI_PRO = ITSOLSAI_PRO.CD_SOLSAI_PRO
  WHERE P.CD_ESPECIE NOT IN (2)
  GROUP BY
    C.CD_ITPRE_MED,
    C.CD_TIP_PRESC,
    P.DS_PRODUTO
)

SELECT
  P.CD_ATENDIMENTO,
  P.CD_SETOR,
  P.NM_PACIENTE,
  P.DT_NASCIMENTO,
  P.CD_SOLSAI_PRO,
  P.IDADE,
  P.DS_PRODUTO  AS PRODUTO_PRESCRITO,
  P.QT_ITPRE_MED,
  P.QTD AS QTD_PRODUTO,
  P.DS_UNIDADE,
  C.DS_COMPONENTE  AS COMPONENTE_PRESCRITO,
  C.QTD_COMPONENTE,
  P.NM_SETOR,
  P.DS_LEITO,
  P.DS_TIP_FRE,
  P.CD_FOR_APL,
  P.NM_MAE,
  P.DS_ITPRE_MED
FROM
  PRODUTOS P
LEFT JOIN
  COMPONENTES C
  ON C.CD_ITPRE_MED = P.CD_ITPRE_MED
)

UNION

SELECT
  CD_ATENDIMENTO,
  CD_SETOR,
  NM_PACIENTE,
  DT_NASCIMENTO,
  CD_SOLSAI_PRO,
  IDADE,
  COMPONENTE_PRESCRITO AS PRODUTO_PRESCRITO,
  QTD_COMPONENTE AS QT_ITPRE_MED,
  QTD_COMPONENTE AS QTD_PRODUTO,
  DS_UNIDADE,
  NULL AS COMPONENTE_PRESCRITO,
  QTD_COMPONENTE,
  NM_SETOR,
  DS_LEITO,
  DS_TIP_FRE,
  CD_FOR_APL,
  NM_MAE,
  DS_ITPRE_MED
FROM (
WITH PRODUTOS AS (
  SELECT
    ATENDIME.CD_ATENDIMENTO,
    PACIENTE.NM_PACIENTE,
    SETOR.CD_SETOR,
    TRUNC(MONTHS_BETWEEN(SYSDATE, PACIENTE.DT_NASCIMENTO) / 12) AS IDADE,
    TO_CHAR(PACIENTE.DT_NASCIMENTO, 'DD/MM/YYYY') DT_NASCIMENTO,
    PRODUTO.DS_PRODUTO AS DS_PRODUTO,
    ITPRE_MED.QT_ITPRE_MED,
    ITSOLSAI_PRO.QT_ATENDIDA AS QTD,
    ITSOLSAI_PRO.CD_ITPRE_MED,
    ITSOLSAI_PRO.CD_TIP_PRESC,
    UNI_PRO.DS_UNIDADE,
    ITPRE_MED.CD_FOR_APL,
    TIP_FRE.DS_TIP_FRE,
    SETOR.NM_SETOR,
    LEITO.DS_LEITO,
    PACIENTE.NM_MAE,
    SOLSAI_PRO.CD_SOLSAI_PRO,
    ITPRE_MED.DS_ITPRE_MED
  FROM
    SOLSAI_PRO
    JOIN ITSOLSAI_PRO ON SOLSAI_PRO.CD_SOLSAI_PRO = ITSOLSAI_PRO.CD_SOLSAI_PRO
    JOIN PRODUTO ON ITSOLSAI_PRO.CD_PRODUTO = PRODUTO.CD_PRODUTO
    JOIN ATENDIME ON ATENDIME.CD_ATENDIMENTO = SOLSAI_PRO.CD_ATENDIMENTO
    JOIN PACIENTE ON ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
    JOIN PRE_MED ON PRE_MED.CD_PRE_MED = SOLSAI_PRO.CD_PRE_MED
    JOIN ITPRE_MED ON ITSOLSAI_PRO.CD_ITPRE_MED = ITPRE_MED.CD_ITPRE_MED
    JOIN TIP_FRE ON ITPRE_MED.CD_TIP_FRE = TIP_FRE.CD_TIP_FRE
    JOIN LEITO ON LEITO.CD_LEITO = ATENDIME.CD_LEITO
    JOIN SETOR ON SETOR.CD_SETOR = PRE_MED.CD_SETOR
    JOIN UNI_PRO ON UNI_PRO.CD_PRODUTO = ITSOLSAI_PRO.CD_PRODUTO
                 AND UNI_PRO.CD_UNI_PRO = ITSOLSAI_PRO.CD_UNI_PRO
  WHERE NOT EXISTS (
      SELECT 1
      FROM CITPRE_MED C
      WHERE C.CD_ITPRE_MED = ITSOLSAI_PRO.CD_ITPRE_MED
        AND C.CD_TIP_PRESC = ITSOLSAI_PRO.CD_TIP_PRESC
    )
    AND SOLSAI_PRO.CD_SOLSAI_PRO = {V_SOLICITACAO}
),

COMPONENTES AS (
  SELECT
    C.CD_ITPRE_MED,
    C.CD_TIP_PRESC,
    P.DS_PRODUTO AS DS_COMPONENTE,
    SUM(ITSOLSAI_PRO.QT_ATENDIDA) AS QTD_COMPONENTE
  FROM
    CITPRE_MED C
    JOIN PRODUTO P ON P.CD_PRODUTO = C.CD_PRODUTO
    JOIN ITSOLSAI_PRO ON C.CD_ITPRE_MED = ITSOLSAI_PRO.CD_ITPRE_MED
                      AND C.CD_TIP_PRESC = ITSOLSAI_PRO.CD_TIP_PRESC
    JOIN SOLSAI_PRO ON SOLSAI_PRO.CD_SOLSAI_PRO = ITSOLSAI_PRO.CD_SOLSAI_PRO
  WHERE P.CD_ESPECIE NOT IN (2)
  GROUP BY
    C.CD_ITPRE_MED,
    C.CD_TIP_PRESC,
    P.DS_PRODUTO
)

SELECT
  P.CD_ATENDIMENTO,
  P.CD_SETOR,
  P.NM_PACIENTE,
  P.DT_NASCIMENTO,
  P.CD_SOLSAI_PRO,
  P.IDADE,
  P.DS_TIP_FRE,
  P.NM_SETOR,
  P.DS_LEITO,
  P.CD_FOR_APL,
  P.DS_PRODUTO AS PRODUTO_PRESCRITO,
  P.QT_ITPRE_MED,
  P.QTD AS QTD_PRODUTO,
  P.DS_UNIDADE,
  C.DS_COMPONENTE AS COMPONENTE_PRESCRITO,
  C.QTD_COMPONENTE,
  P.NM_MAE,
  P.DS_ITPRE_MED
FROM
  PRODUTOS P
LEFT JOIN
  COMPONENTES C
  ON C.CD_ITPRE_MED = P.CD_ITPRE_MED
)
WHERE COMPONENTE_PRESCRITO LIKE ('SORO%100%')
  AND PRODUTO_PRESCRITO NOT LIKE ('SORO%100%')


        UPDATE paciente
        SET   cd_identidade_genero   = 1
        WHERE cd_paciente = 111743



                SELECT * FROM DBAMV.IDENTIDADE_GENERO


                      SELECT * FROM paciente  WHERE cd_paciente = 111743


                             SELECT * FROM  aviso_cirurgia
                             WHERE cd_aviso_cirurgia = 59431

                             UPDATE aviso_cirurgia
                             SET   cd_identidade_genero = 1
                             WHERE   cd_aviso_cirurgia = 59431



                        <DS_SCRIPT>
-- DESCRIO...: GLOBAL-2575 - Cria o campo TP_SEXO na tabela IDENTIDADE_GENERO
-- RESPONSAVEL.: GABRIEL F.F LOBAO
-- DATA........: 01/08/2022
-- APLICAO...: GLOBAL - Cadastro de Identidade de Gnero
--</DS_SCRIPT>
--<USUARIO=DBAMV>


ALTER TABLE DBAMV.IDENTIDADE_GENERO  ADD CD_TP_SEXO VARCHAR2(1) DEFAULT NULL
/
ALTER TABLE DBAMV.IDENTIDADE_GENERO
    ADD CONSTRAINT CNT_IDENTIDADE_GENERO_2_FK FOREIGN KEY (CD_TP_SEXO)
        REFERENCES DBAMV.TIPO_SEXO (TP_SEXO)
/
CREATE INDEX DBAMV.IND_IDENTIDADE_GENERO_2_FK
ON DBAMV.IDENTIDADE_GENERO (CD_TP_SEXO)
TABLESPACE mv2000_i
COMPUTE STATISTICS
/
COMMENT ON COLUMN dbamv.IDENTIDADE_GENERO.CD_TP_SEXO IS 'Sigla do sexo biolgico associado.'
/
