CREATE OR REPLACE PROCEDURE dbamv.prc_ajusta_tiss_atd_sw

   IS

BEGIN

EXECUTE IMMEDIATE 'ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_ATENDIMENTO DISABLE';
EXECUTE IMMEDIATE 'ALTER TRIGGER MVINTEGRA.TRG_IMVW_OUT_ATENDIMENTO DISABLE';

UPDATE atendime SET tp_atendimento_tiss = NULL WHERE tp_atendimento_tiss IS NOT NULL
AND dt_atendimento >= To_Date('01/07/2024 00:00:00', 'DD/MM/YYYY HH24:MI:SS')
AND DT_ATENDIMENTO = SYSDATE-1
AND CD_CONVENIO IN (3,5,7,8,10,15,16,19,26,35,48,53,54,74,78,79);
COMMIT;
EXECUTE IMMEDIATE 'ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_ATENDIMENTO ENABLE';
EXECUTE IMMEDIATE 'ALTER TRIGGER MVINTEGRA.TRG_IMVW_OUT_ATENDIMENTO ENABLE';



END;
/

