
SELECT  DISTINCT
        RF.CD_ATENDIMENTO,
        ITF.CD_PRO_FAT,
        ITF.VL_UNITARIO AS MAX_VALOR,
        RF.CD_REG_FAT,
        itf.cd_prestador,
        To_Date(itf.dt_lancamento, 'dd/mm/rrrr') dt_lancamento
--      LAST_VALUE(ITF.CD_PRESTADOR) OVER (
--            PARTITION BY RF.CD_ATENDIMENTO, ITF.CD_PRO_FAT
--            ORDER BY ITF.DT_LANCAMENTO ASC
--            ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
--        ) AS LAST_CD_PRESTADOR
    FROM REG_FAT RF
    INNER JOIN ITREG_FAT ITF
        ON RF.CD_REG_FAT = ITF.CD_REG_FAT
    WHERE RF.CD_ATENDIMENTO = 984179
    AND ITF.CD_PRO_FAT = 20010141
  --  AND ITF.CD_PRESTADOR IS NOT NULL

 --  WHERE rn = 2
