SELECT *
FROM ATENDIME
-- WHERE CD_LEITO = '15'
 -- AND ROWNUM <= 10
ORDER BY CD_ATENDIMENTO DESC

FETCH FIRST 100 ROWS ONLY;
/


-- 1. DESABILITAR O TRIGGER
ALTER TRIGGER DBAMV.CONSISTE_TP_OCUPACAO DISABLE;
/

-- 2. VERIFICAR ANTES DE ATUALIZAR
SELECT CD_LEITO,
       DS_LEITO,
       TP_OCUPACAO
FROM LEITO
WHERE CD_LEITO = 107
  AND DS_LEITO = 'B 15';
/

-- 3. EXECUTAR O UPDATE
UPDATE LEITO
SET TP_OCUPACAO = 'V'
WHERE CD_LEITO = 107
  AND DS_LEITO = 'B 15';
/

-- 4. CONFIRMAR
COMMIT;
/

-- 5. REABILITAR O TRIGGER (OBRIGATÓRIO!)
ALTER TRIGGER DBAMV.CONSISTE_TP_OCUPACAO ENABLE;
/

-- 6. VERIFICAR SE O TRIGGER ESTÁ ATIVO NOVAMENTE
SELECT TRIGGER_NAME,
       STATUS
FROM ALL_TRIGGERS
WHERE TRIGGER_NAME = 'CONSISTE_TP_OCUPACAO'
  AND OWNER = 'DBAMV';