SELECT * FROM itped_rx
WHERE cd_ped_rx = 129127


ALTER TRIGGER mvintegra.trg_imvw_sai_itsolic_psdi DISABLE;


UPDATE itped_rx 
SET cd_prestador = 2947 
WHERE cd_ped_rx = 129127;
COMMIT;


ALTER TRIGGER mvintegra.trg_imvw_sai_itsolic_psdi ENABLE;


-- PRIMEIRO PASSO PRECISAMOS EXCLUIR O ITEM DO PEDIDO --
-- OBS: CONFIRMAR ANTES SE É ISSO PQ NAO PEGUEI UM EXEMPLO COM LAUDO

ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_SOLIC_PSDI DISABLE; 

DELETE FROM LAUDO_RX 
WHERE CD_PED_RX = 126759;

ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_SOLIC_PSDI ENABLE;
ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_ITSOLIC_PSDI DISABLE;

DELETE FROM ITPED_RX 
WHERE CD_PED_RX = 126759;

ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_ITSOLIC_PSDI ENABLE;
ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_SOLIC_PSDI DISABLE;

DELETE FROM PED_RX 
WHERE CD_PED_RX = 126759;

ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_SOLIC_PSDI ENABLE;