SELECT * FROM itped_rx
WHERE cd_ped_rx = 160622;

ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_ITSOLIC_PSDI DISABLE; 

DELETE FROM itped_rx
WHERE cd_ped_rx = '170253' and cd_exa_rx = '935'; 

ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_ITSOLIC_PSDI ENABLE;
