
SELECT * FROM itped_rx
WHERE cd_ped_rx = 155539;

DELETE FROM  itped_rx
WHERE  cd_ped_rx = 155539;

ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_ATENDIMENTO DISABLE;
ALTER TRIGGER MVINTEGRA.TRG_IMVW_OUT_ATENDIMENTO DISABLE;

ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_ITSOLIC_PSDI DISABLE;


ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_ATENDIMENTO ENABLE;
ALTER TRIGGER MVINTEGRA.TRG_IMVW_OUT_ATENDIMENTO ENABLE;

ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_ITSOLIC_PSDI ENABLE;

SELECT * FROM PED_RX
WHERE CD_PED_RX = 155539;

DELETE FROM PED_RX
WHERE CD_PED_RX = '155539' AND cd_atendimento = '1005484';


___________________________________________________________________________________


SELECT * FROM ITPED_RX  
HERE CD_PED_RX = 148534 AND CD_EXA_RX = 813; 

-- comando para excluir um exame de um pedido -- *
ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_ITSOLIC_PSDI DISABLE;  
ALTER TABLE MVTO_ESTOQUE DISABLE CONSTRAINT ITMVTO_ESTOQUE_ITPED_RX_FK;
 
DELETE FROM ITPED_RX  WHERE CD_PED_RX = 148534 AND CD_EXA_RX = 813;

ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_ITSOLIC_PSDI ENABLE;  
ALTER TABLE MVTO_ESTOQUE ENABLE CONSTRAINT ITMVTO_ESTOQUE_ITPED_RX_FK;

/* só para te explicar esse caso não tinha registros na tabela ITMVTO_ESTOQUE, mas quando tentava deletar ele não 
deixava por causa da integridade. Por isso que eu tive que rodar esse  para desabilitar a chave e conseguir deletar o exame */

ALTER TABLE MVTO_ESTOQUE DISABLE *CONSTRAINT ITMVTO_ESTOQUE_ITPED_RX_FK*;
