SELECT
  GUIA.CD_GUIA,
	NVL(GUIA.NR_GUIA, 'NR NÃO INFORMADO') NR_GUIA,
    IT_GUIA.DT_GERACAO DT_REQUISICAO,
	GUIA.DT_AUTORIZACAO,
	NVL(GUIA.DT_SOLICITACAO,IT_GUIA.DT_GERACAO) DT_SOLICITACAO,

  TRUNC(GUIA.DT_SOLICITACAO-IT_GUIA.DT_GERACAO)TEMPO_SOLICITACAO,
  TRUNC(GUIA.DT_AUTORIZACAO-GUIA.DT_SOLICITACAO)TEMPO_AUTORIZACAO,

	GUIA.DT_NEGACAO,
	GUIA.DT_SUSPENSAO,
  trunc(sysdate) - trunc(NVL(GUIA.DT_SOLICITACAO,IT_GUIA.DT_GERACAO)) dias_pendente,
  trunc(GUIA.DT_VALIDADE) - trunc(GUIA.DT_SOLICITACAO) dias_vencimento,
	GUIA.DT_VALIDADE DT_VAL_GUIA,
  GUIA.TP_GUIA TIPO_DA_GUIA,
  NVL(GUIA.TP_SITUACAO,'P') SITUACAO_DA_GUIA,
  CONVENIO.CD_CONVENIO,
	CONVENIO.NM_CONVENIO NM_CONVENIO,
  ATENDIME.CD_ATENDIMENTO,
	ATENDIME.DT_ATENDIMENTO,
	ATENDIME.DT_ALTA DT_ALTA,
  ATENDIME.TP_ATENDIMENTO,
  CASE
    WHEN ATENDIME.TP_ATENDIMENTO IN ('I','B') THEN 'INTERNO'
    ELSE 'EXTERNO'
  END TP_ORIGEM_ATENDIMENTO,
	PACIENTE.CD_PACIENTE CD_PACIENTE,
	PACIENTE.NM_PACIENTE NM_PACIENTE,
	LEITO.CD_LEITO CD_LEITO,
	LEITO.DS_LEITO DS_LEITO,
	PRESTADOR.CD_PRESTADOR CD_PRESTADOR,
	PRESTADOR.NM_PRESTADOR NM_PRESTADOR,
  IT_GUIA.CD_IT_GUIA,
  PRO_FAT.CD_PRO_FAT,
  NVL(PRO_FAT.DS_PRO_FAT,'NÃO INFORMADO') DS_PRO_FAT,
  IT_GUIA.QT_AUTORIZADO,
  IT_GUIA.DS_OBSERVACAO DS_OBSERVACAO_ITEM,
  IT_GUIA.QT_AUTORIZADA_CONVENIO,
  IT_GUIA.DT_GERACAO,
  GRU_PRO.CD_GRU_PRO,
  NVL(GRU_PRO.DS_GRU_PRO,'NÃO INFORMADO') DS_GRU_PRO,
  GRU_FAT.CD_GRU_FAT,
  nvl(GRU_FAT.DS_GRU_FAT,'NÃO INFORMADO') DS_GRU_FAT,
  CASE
     WHEN EXISTS(SELECT 1
                   FROM REG_FAT
                  WHERE REG_FAT.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO
                        AND NVL(REG_FAT.SN_FECHADA,'N') = 'N') THEN 'NÃO'
     WHEN EXISTS(SELECT 1
                   FROM ITREG_AMB
                  WHERE ITREG_AMB.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO
                        AND NVL(ITREG_AMB.SN_FECHADA,'N') = 'N') THEN 'NÃO'
    ELSE 'SIM'
  END CONTA_FECHADA
FROM
  DBAMV.IT_GUIA
  INNER JOIN DBAMV.GUIA ON IT_GUIA.CD_GUIA = GUIA.CD_GUIA
  --                         AND GUIA.TP_SITUACAO NOT IN ('A','N')   --DESCONSIDERA AUTORIZADA   E NEGADA

  LEFT JOIN DBAMV.CONVENIO ON GUIA.CD_CONVENIO = CONVENIO.CD_CONVENIO

  LEFT JOIN DBAMV.ATENDIME ON GUIA.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO
  LEFT JOIN DBAMV.PACIENTE ON ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
  LEFT JOIN DBAMV.PRESTADOR ON ATENDIME.CD_PRESTADOR = PRESTADOR.CD_PRESTADOR
	LEFT JOIN DBAMV.LEITO ON ATENDIME.CD_LEITO = LEITO.CD_LEITO
  LEFT JOIN DBAMV.UNID_INT ON UNID_INT.CD_UNID_INT = LEITO.CD_UNID_INT

  LEFT JOIN DBAMV.PRO_FAT ON PRO_FAT.CD_PRO_FAT = IT_GUIA.CD_PRO_FAT
  LEFT JOIN DBAMV.GRU_PRO ON PRO_FAT.CD_GRU_PRO = GRU_PRO.CD_GRU_PRO
  LEFT JOIN DBAMV.GRU_FAT ON GRU_PRO.CD_GRU_FAT = GRU_FAT.CD_GRU_FAT

