SELECT
  UPPER(TO_CHAR(DADOS.DH_ENTRADA,'d')||'-'||TO_CHAR(DADOS.DH_ENTRADA,'DAY')) DIA_SEMANA,
  to_char(trunc(sysdate) + rownum/24, 'HH24')dd,
SUM(CASE
    WHEN to_char(trunc(sysdate) + rownum/24, 'HH24') BETWEEN to_char(DADOS.DH_ENTRADA,'HH24') AND to_char(DADOS.DH_INICIO_LIMPEZA,'HH24') THEN 1
    ELSE 0
END) TOTAL


FROM   
(SELECT
  MULTI_EMPRESAS.CD_MULTI_EMPRESA CD_EMPRESA,

  MULTI_EMPRESAS.DS_MULTI_EMPRESA NM_EMPRESA,

  PACIENTE.CD_PACIENTE CD_PACIENTE,

  PACIENTE.NM_PACIENTE NM_PACIENTE,

  ATENDIME.CD_ATENDIMENTO CD_ATENDIMENTO,

  ATENDIME.TP_ATENDIMENTO,

  CASE ATENDIME.TP_ATENDIMENTO
    WHEN 'A' THEN 'AMBULATÓRIO'
    WHEN 'U' THEN 'URGÊNCIA'
    WHEN 'I' THEN 'INTERNAÇÃO'
    WHEN 'E' THEN 'EXTERNO'
    WHEN 'H' THEN 'HOME CARE'
    WHEN 'B' THEN 'BUSCA ATIVA'
    WHEN 'S' THEN 'SUS AIH'
  END DS_TP_ATENDIMENTO,

  ORI_ATE.DS_ORI_ATE,

  TRUNC(ATENDIME.DT_ATENDIMENTO) + (ATENDIME.HR_ATENDIMENTO - TRUNC(ATENDIME.HR_ATENDIMENTO)) DH_ATENDIMENTO,

  TRUNC(ATENDIME.DT_ALTA) + (ATENDIME.HR_ALTA - TRUNC(ATENDIME.HR_ALTA)) DT_ALTA,

  AVISO_CIRURGIA.CD_AVISO_CIRURGIA,

  CONVENIO.CD_CONVENIO CD_CONVENIO,

  CONVENIO.NM_CONVENIO NM_CONVENIO,

  DECODE(CONVENIO.TP_CONVENIO,'C','CONVÊNIO','P','PARTICULAR','H','SUS','A','SUS',CONVENIO.TP_CONVENIO) DS_TIPO_CONVENIO,

  CASE AVISO_CIRURGIA.TP_CIRURGIAS
    WHEN 'U' THEN 'URGÊNCIA'
    WHEN 'M' THEN 'EMERGÊNCIA'
    WHEN 'E' THEN 'ELETIVA'
  END DS_TIPO_URGENCIA,

  AVISO_CIRURGIA.DT_REALIZACAO DH_CIRURGIA,

  CEIL(TO_CHAR(AVISO_CIRURGIA.DT_REALIZACAO,'MM') / 2) DS_BIMESTRE_CIRURGIA,

  CEIL(TO_CHAR(AVISO_CIRURGIA.DT_REALIZACAO,'MM') / 3) DS_TRIMESTRE_CIRURGIA,

  CEIL(TO_CHAR(AVISO_CIRURGIA.DT_REALIZACAO,'MM') / 4) DS_QUADRIMESTRE_CIRURGIA,

  CEIL(TO_CHAR(AVISO_CIRURGIA.DT_REALIZACAO,'MM') / 6) DS_SEMESTRE_CIRURGIA,

  TO_CHAR(AVISO_CIRURGIA.DT_REALIZACAO,'D-Dy') DS_DIA_SEMANA_CIRURGIA,

  TO_CHAR(AVISO_CIRURGIA.DT_REALIZACAO,'DD-Dy') DS_DIA_DSEMANA_CIRURGIA,

  CIRURGIA.CD_CIRURGIA CD_PROCEDIMENTO,

  CIRURGIA.DS_CIRURGIA DS_PROCEDIMENTO,

  SUB_GRUPO_CIRURGIA.CD_SUB_GRUPO_CIRURGIA CD_SGRUPO_PROCEDIMENTO,

  NVL(SUB_GRUPO_CIRURGIA.DS_SUB_GRUPO_CIRURGIA,'NÃO INFORMADO') DS_SGRUPO_PROCEDIMENTO,

  SAL_CIR.CD_SAL_CIR CD_SALA_CIRURGICA,

  SAL_CIR.DS_SAL_CIR NM_SALA_CIRURGICA,

  CEN_CIR.CD_CEN_CIR CD_CENTRO_CIRURGICO,

  CEN_CIR.DS_CEN_CIR NM_CENTRO_CIRURGICO,

  ESPECIALID.CD_ESPECIALID CD_ESPECIALIDADE,

  NVL(ESPECIALID.DS_ESPECIALID,'NÃO INFORMADO') DS_ESPECIALIDADE,

  CIRURGIA.TP_CIRURGIA TP_PORTE_CIRURGIA,

  DECODE(CIRURGIA.TP_CIRURGIA,'P','PEQUENA','M','MÉDIA','G','GRANDE','E','ESPECIAL') DS_PORTE_CIRURGIA,

  AVISO_CIRURGIA.DT_REALIZACAO DH_ENTRADA,

  AVISO_CIRURGIA.DT_INICIO_ANESTESIA DH_INICIO_ANESTESIA,

  AVISO_CIRURGIA.DT_INICIO_CIRURGIA DH_INICIO_CIRURGIA,

  AVISO_CIRURGIA.DT_FIM_CIRURGIA DH_FIM_CIRURGIA,

  AVISO_CIRURGIA.DT_FIM_ANESTESIA DH_FIM_ANESTESIA,

  AVISO_CIRURGIA.DT_SAIDA_SAL_CIR,

  AVISO_CIRURGIA.DT_INICIO_LIMPEZA DH_INICIO_LIMPEZA,

  AVISO_CIRURGIA.DT_FIM_LIMPEZA DH_FIM_LIMPEZA,

  ---Tempos entre os processos para mensurar ocupação de sala, desde a entrada de sala até o final de limpeza
  (AVISO_CIRURGIA.DT_INICIO_ANESTESIA - AVISO_CIRURGIA.DT_REALIZACAO)      * 86400 QT_SEG_ENT_SAL_INI_ANE,   /*Entrada Sala x Início Anestesia*/
  (AVISO_CIRURGIA.DT_INICIO_CIRURGIA  - AVISO_CIRURGIA.DT_INICIO_ANESTESIA)* 86400 QT_SEG_INI_ANE_INI_CIR,   /*Início Anestesia x Início Cirurgia*/
  (AVISO_CIRURGIA.DT_FIM_CIRURGIA     - AVISO_CIRURGIA.DT_INICIO_CIRURGIA) * 86400 QT_SEG_INI_CIR_FIM_CIR,   /*Início Cirurgia x Fim Cirurgia*/
  (AVISO_CIRURGIA.DT_FIM_ANESTESIA    - AVISO_CIRURGIA.DT_FIM_CIRURGIA)    * 86400 QT_SEG_FIM_CIR_FIM_ANE,   /*Fim Cirurgia x Fim Anestesia*/
  (AVISO_CIRURGIA.DT_SAIDA_SAL_CIR    - AVISO_CIRURGIA.DT_FIM_ANESTESIA)   * 86400 QT_SEG_FIM_ANE_SAI_SAL,   /*Fim Anestesia x Saída Sala */
  (AVISO_CIRURGIA.DT_INICIO_LIMPEZA   - AVISO_CIRURGIA.DT_SAIDA_SAL_CIR)   * 86000 QT_SEG_SAI_SAL_INI_LIM,   /*Saída Sala x Início Limpeza*/
  (AVISO_CIRURGIA.DT_FIM_LIMPEZA      - AVISO_CIRURGIA.DT_INICIO_LIMPEZA)  * 86400 QT_SEG_INI_LIM_FIM_LIM,   /*Início Limpeza x Fim Limpeza*/
  (AVISO_CIRURGIA.DT_FIM_LIMPEZA      - AVISO_CIRURGIA.DT_REALIZACAO)      * 86400 QT_SEG_ENT_SAL_FIM_LIM,   /*Total Ocupação x (Entrada Sala até Fim Limpeza)*/
  --Outros tempos interessantes
  (AVISO_CIRURGIA.DT_SAIDA_SAL_CIR    - AVISO_CIRURGIA.DT_REALIZACAO)      * 86400 QT_SEG_ENT_SAL_SAI_SAL,   /*Entrada Sala x Saída Sala*/
  (AVISO_CIRURGIA.DT_INICIO_CIRURGIA  - AVISO_CIRURGIA.DT_REALIZACAO)      * 86400 QT_SEG_ENT_SAL_INI_CIR,   /*Entrada Sala x Início Cirurgia*/
  (AVISO_CIRURGIA.DT_FIM_ANESTESIA    - AVISO_CIRURGIA.DT_INICIO_ANESTESIA)* 86400 QT_SEG_INI_ANE_FIM_ANE,   /*Início Anestesia x Fim Anestesia*/
  (AVISO_CIRURGIA.DT_SAIDA_SAL_CIR    - AVISO_CIRURGIA.DT_FIM_CIRURGIA)    * 86400 QT_SEG_FIM_CIR_SAI_SAL,   /*Fim Cirurgia x Saída Sala*/
  (AVISO_CIRURGIA.DT_FIM_LIMPEZA      - AVISO_CIRURGIA.DT_SAIDA_SAL_CIR)   * 86400 QT_SEG_INI_CIR_FIM_LIM,   /*Saída Sala x Término Limpeza*/

  CASE
    WHEN  (DT_FIM_CIRURGIA - DT_INICIO_CIRURGIA) * 24 <= 1 THEN '1) ATÉ 1 HORA'
    WHEN  (DT_FIM_CIRURGIA - DT_INICIO_CIRURGIA) * 24 <= 2 THEN '2) ATÉ 2 HORAS'
    WHEN  (DT_FIM_CIRURGIA - DT_INICIO_CIRURGIA) * 24 <= 3 THEN '3) ATÉ 3 HORAS'
    WHEN  (DT_FIM_CIRURGIA - DT_INICIO_CIRURGIA) * 24 <= 4 THEN '4) ATÉ 4 HORAS'
    WHEN  (DT_FIM_CIRURGIA - DT_INICIO_CIRURGIA) * 24 <= 5 THEN '5) ATÉ 5 HORAS'
    WHEN  (DT_FIM_CIRURGIA - DT_INICIO_CIRURGIA) * 24 <= 6 THEN '6) ATÉ 6 HORAS'
    WHEN  (DT_FIM_CIRURGIA - DT_INICIO_CIRURGIA) * 24 >  6 THEN '7) ACIMA DE 6 HORAS'
  END DS_GRUPO_TEMPO_PROC_CIRURGICO,

  MOT_CANC.CD_MOT_CANC CD_MOTIVO_ATRASO,

  MOT_CANC.DS_MOT_CANC DS_MOTIVO_ATRASO,

  DECODE(AVISO_CIRURGIA.CD_MOT_CANC_ATRASO,NULL,'NÃO','SIM') DS_SN_ATRASO,

  CASE
    WHEN NVL(ATENDIME.SN_OBITO,'N') = 'S'
          AND TRUNC(ATENDIME.DT_ALTA) + (ATENDIME.HR_ALTA - TRUNC(ATENDIME.HR_ALTA)) BETWEEN DT_INICIO_CIRURGIA AND DT_FIM_CIRURGIA THEN 'SIM'
    ELSE 'NÃO'
  END DS_SN_OBITO_TRANSOPERATORIO,

  DECODE(NVL(CIRURGIA_AVISO.SN_PRINCIPAL,'N'),'N','NÃO','S','SIM') DS_SN_PROC_PRINCIPAL,

  POR_ANE.CD_POR_ANE CD_PORTE_ANESTESICO,

  NVL(POR_ANE.DS_POR_ANE,'NÃO INFORMADO') DS_PORTE_ANESTESICO,

  ATI_MED.CD_ATI_MED CD_ATIVIDADE_PRESTADOR,

  ATI_MED.DS_ATI_MED DS_ATIVIDADE_PRESTADOR,

  PRESTADOR.CD_PRESTADOR CD_PRESTADOR,

  PRESTADOR.NM_PRESTADOR NM_PRESTADOR,

  CASE WHEN AGE_CIR.CD_AGE_CIR IS NULL THEN 'SIM' ELSE 'NÃO' END DS_SN_AGENDAMENTO,

  CASE CIRURGIA_AVISO.TP_NATUREZA
    WHEN 'L' THEN 'LIMPA'
    WHEN 'C' THEN 'CONTAMINADA'
    WHEN 'I' THEN 'INFECTADA'
    WHEN 'P' THEN 'POTENCIALMENTE CONTAMINADA'
    WHEN 'N' THEN 'NENHUMA'
    WHEN NULL THEN CIRURGIA_AVISO.TP_NATUREZA
    ELSE 'NÃO INFORMADO'
  END DS_GRAU_CONTAMINACAO,

  COALESCE(TIP_ANEST.DS_TIP_ANEST,'NÃO INFORMADO') DS_TIPO_ANESTESIA,
  CASE
    WHEN ATENDIME.SN_OBITO = 'S'
    AND TRUNC(ATENDIME.DT_ALTA) + (ATENDIME.HR_ALTA - TRUNC(ATENDIME.HR_ALTA)) BETWEEN AVISO_CIRURGIA.DT_REALIZACAO AND AVISO_CIRURGIA.DT_SAIDA_SAL_CIR THEN 1
  END QT_OBITO_TRANSOPERATORIO,

  CASE
    WHEN ATENDIME.SN_OBITO = 'S' THEN 1
  END QT_TOTAL_OBITOS,

  1 QT_TOTAL_REGISTRO,

 case
    when CIRURGIA_AVISO.SN_REOP = 'S' then
      case when :CD_CIRURGIA IS NULL and :CD_CIRURGIA_DESC IS NULL then 1
      else
      case when :CD_CIRURGIA IS NOT NULL and :CD_CIRURGIA_DESC IS NULL
                AND CIRURGIA.CD_CIRURGIA  IN ( ---traz selecionadas
                              (SELECT
                                     REGEXP_SUBSTR(:CD_CIRURGIA,'[^,]+', 1, LEVEL)
                                  FROM
                                    DUAL
                                 CONNECT BY
                                   REGEXP_SUBSTR(:CD_CIRURGIA, '[^,]+', 1, LEVEL) IS NOT NULL))
               THEN 1

            when :CD_CIRURGIA IS NULL and :CD_CIRURGIA_DESC IS NOT NULL
                AND CIRURGIA.CD_CIRURGIA not IN ( ---traz selecionadas
                              (SELECT
                                     REGEXP_SUBSTR(:CD_CIRURGIA_DESC,'[^,]+', 1, LEVEL)
                                  FROM
                                    DUAL
                                 CONNECT BY
                                   REGEXP_SUBSTR(:CD_CIRURGIA_DESC, '[^,]+', 1, LEVEL) IS NOT NULL))
               THEN 1


              ELSE 0 end END end QT_REOP_SIM,

  --DECODE(CIRURGIA_AVISO.SN_REOP,'S',1,0) QT_REOP_SIM,


  DECODE(CIRURGIA_AVISO.SN_REOP,'S',0,1) QT_REOP_NAO,

  DECODE(AVISO_CIRURGIA.CD_MOT_CANC_ATRASO,NULL,1,0) QT_ATRASO_NAO,
  DECODE(AVISO_CIRURGIA.CD_MOT_CANC_ATRASO,NULL,0,1) QT_ATRASO_SIM,

  (SELECT MAX(X.CD_MOV_INT)
    FROM MOV_INT X
  WHERE X.CD_ATENDIMENTO = AVISO_CIRURGIA.CD_ATENDIMENTO
        AND TRUNC(X.DT_MOV_INT) + (X.HR_MOV_INT - TRUNC(X.HR_MOV_INT)) <= AVISO_CIRURGIA.DT_REALIZACAO + 59/86400  --acrescentado 59 segundos porque o campo DT_REALIZACAO não considera segundos
        AND X.TP_MOV IN ('I','O')
        ) CD_MOV_INT_ORIGEM,

  (SELECT MIN(X.CD_MOV_INT)
     FROM MOV_INT X
    WHERE X.CD_ATENDIMENTO = AVISO_CIRURGIA.CD_ATENDIMENTO
          AND TRUNC(X.DT_MOV_INT) + (X.HR_MOV_INT - TRUNC(X.HR_MOV_INT)) >= AVISO_CIRURGIA.DT_REALIZACAO + 59/86400 --acrescentado 59 segundos porque o campo DT_SAIDA_SAL_CIR não considera segundos
          AND TRUNC(X.DT_MOV_INT) + (X.HR_MOV_INT - TRUNC(X.HR_MOV_INT)) < AVISO_CIRURGIA.DT_SAIDA_SAL_CIR + 59/86400 + 12/24 --verifica a próxima movimentação até 12 horas.
          AND X.TP_MOV IN ('I','O')) CD_MOV_INT_DESTINO,

   --RANK DAS CIRURGIAS POR CENTRO, SALA E DATA. PARA OBTER O REGISTRO DA PRIMEIRA CIRURGIA DO DIA
   RANK() OVER (PARTITION BY AVISO_CIRURGIA.CD_CEN_CIR, AVISO_CIRURGIA.CD_SAL_CIR,TRUNC(AVISO_CIRURGIA.DT_INICIO_CIRURGIA) ORDER BY AVISO_CIRURGIA.DT_INICIO_CIRURGIA) RANK_HR_INI_PRIM_CIR ,

   --RANK DAS CIRURGIAS POR CENTRO, SALA E DATA. PARA OBTER O REGISTRO DA ULTIMA CIRURGIA DO DIA
   RANK() OVER (PARTITION BY AVISO_CIRURGIA.CD_CEN_CIR, AVISO_CIRURGIA.CD_SAL_CIR,TRUNC(AVISO_CIRURGIA.DT_FIM_CIRURGIA) ORDER BY AVISO_CIRURGIA.DT_FIM_CIRURGIA DESC) RANK_HR_FIM_ULT_CIR,

   CASE
     WHEN TRUNC(nvl(ATENDIME.DT_ALTA,sysdate))- TRUNC(ATENDIME.DT_ATENDIMENTO) >= 2 THEN '2 dias ou mais'
     WHEN TRUNC(nvl(ATENDIME.DT_ALTA,sysdate))- TRUNC(ATENDIME.DT_ATENDIMENTO) < 2 THEN 'Até 1 dia'
   end grupo_dias_int,

   TRUNC(MONTHS_BETWEEN(AVISO_CIRURGIA.DT_REALIZACAO,PACIENTE.DT_NASCIMENTO) / 12) IDADE,
   case
     when TRUNC(MONTHS_BETWEEN(AVISO_CIRURGIA.DT_REALIZACAO,PACIENTE.DT_NASCIMENTO) / 12) > 60 then 'Acima de 60 anos'
     else 'Até 60 anos'
   end grupo_idade
FROM
   DBAMV.AVISO_CIRURGIA

   INNER JOIN DBAMV.CIRURGIA_AVISO ON AVISO_CIRURGIA.CD_AVISO_CIRURGIA = CIRURGIA_AVISO.CD_AVISO_CIRURGIA

   INNER JOIN DBAMV.MULTI_EMPRESAS ON AVISO_CIRURGIA.CD_MULTI_EMPRESA = MULTI_EMPRESAS.CD_MULTI_EMPRESA

   INNER JOIN DBAMV.SAL_CIR ON AVISO_CIRURGIA.CD_SAL_CIR = SAL_CIR.CD_SAL_CIR

   INNER JOIN DBAMV.CEN_CIR ON AVISO_CIRURGIA.CD_CEN_CIR = CEN_CIR.CD_CEN_CIR

   INNER JOIN DBAMV.ATENDIME ON AVISO_CIRURGIA.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO

   INNER JOIN DBAMV.PACIENTE ON ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE

   INNER JOIN DBAMV.CIRURGIA ON CIRURGIA_AVISO.CD_CIRURGIA = CIRURGIA.CD_CIRURGIA

   LEFT JOIN DBAMV.PRESTADOR_AVISO ON CIRURGIA_AVISO.CD_CIRURGIA_AVISO = PRESTADOR_AVISO.CD_CIRURGIA_AVISO
                                       AND PRESTADOR_AVISO.CD_ATI_MED = '01'     /*INFORMAR A ATIVIDADE MEDICA REF. AO CIRURGIÃO GERALMENTE É 01 MAS TEM CASOS QUE É 00*/
                                       AND NVL(PRESTADOR_AVISO.SN_PRINCIPAL,'N') = 'S' /*SOMENTE PRESTADOR PRINCIPAL DA ATIVIDADE*/


   LEFT JOIN DBAMV.ATI_MED ON PRESTADOR_AVISO.CD_ATI_MED = ATI_MED.CD_ATI_MED

   LEFT JOIN DBAMV.SUB_GRUPO_CIRURGIA ON CIRURGIA.CD_SUB_GRUPO_CIRURGIA = SUB_GRUPO_CIRURGIA.CD_SUB_GRUPO_CIRURGIA

   LEFT JOIN DBAMV.ESPECIALID ON CIRURGIA_AVISO.CD_ESPECIALID = ESPECIALID.CD_ESPECIALID

   LEFT JOIN DBAMV.MOT_CANC ON AVISO_CIRURGIA.CD_MOT_CANC_ATRASO = MOT_CANC.CD_MOT_CANC /*MOTIVO DE ATRASO USA A MESMA TABELA DE MOTIVO CANCELAMENTO*/

   LEFT JOIN PRO_FAT ON CIRURGIA.CD_PRO_FAT = PRO_FAT.CD_PRO_FAT

   LEFT JOIN POR_ANE ON PRO_FAT.CD_POR_ANE = POR_ANE.CD_POR_ANE

   LEFT JOIN PRESTADOR ON PRESTADOR_AVISO.CD_PRESTADOR = PRESTADOR.CD_PRESTADOR

   LEFT JOIN AGE_CIR ON AVISO_CIRURGIA.CD_AVISO_CIRURGIA = AGE_CIR.CD_AVISO_CIRURGIA

   LEFT JOIN CONVENIO ON CIRURGIA_AVISO.CD_CONVENIO = CONVENIO.CD_CONVENIO

   LEFT JOIN TIP_ANEST ON AVISO_CIRURGIA.CD_TIP_ANEST = TIP_ANEST.CD_TIP_ANEST

   LEFT JOIN ORI_ATE ON ATENDIME.CD_ORI_ATE = ORI_ATE.CD_ORI_ATE
WHERE
  1=1
  AND AVISO_CIRURGIA.TP_SITUACAO = 'R' /*SOMENTE CIRURGIA REALIZADA */
  AND AVISO_CIRURGIA.CD_CEN_CIR = 2 /*ADICIONADO FILTRO DEVIDO A INCLUSAO DO PROCESSO DA HEMODINAMICA -- Marcelo 13062024 */
  --and aviso_cirurgia.cd_atendimento = 695920
 -- AND AVISO_CIRURGIA.DT_REALIZACAO >= TO_DATE('01/01/2024','DD/MM/YYYY')
  --And AVISO_CIRURGIA.CD_ATENDIMENTO = 700205
  --and CIRURGIA.CD_CIRURGIA in (3143,2960)
  
) dados
  left join (	SELECT
                MOV_INT.CD_MOV_INT,
                TRUNC(MOV_INT.DT_MOV_INT) + (MOV_INT.HR_MOV_INT - TRUNC(MOV_INT.HR_MOV_INT)) DH_MOV_INT,
                UNIDADE_DESTINO.CD_UNID_INT ,
                UNIDADE_DESTINO.DS_UNID_INT ,
                MOV_INT.TP_MOV,
                LEITO_DESTINO.CD_LEITO ,
                LEITO_DESTINO.DS_LEITO ,
                NVL(LEITO_DESTINO.SN_EXTRA,'N') SN_EXTRA,
                MOV_INT.CD_ATENDIMENTO
              FROM
                DBAMV.MOV_INT
                INNER JOIN DBAMV.LEITO LEITO_DESTINO ON MOV_INT.CD_LEITO = LEITO_DESTINO.CD_LEITO
                INNER JOIN DBAMV.UNID_INT UNIDADE_DESTINO ON LEITO_DESTINO.CD_UNID_INT = UNIDADE_DESTINO.CD_UNID_INT
              WHERE
                1=1
                AND MOV_INT.TP_MOV IN ('I','O')) mov_origem on dados.cd_mov_int_origem = mov_origem.cd_mov_int

  left join (	SELECT
                MOV_INT.CD_MOV_INT,
                TRUNC(MOV_INT.DT_MOV_INT) + (MOV_INT.HR_MOV_INT - TRUNC(MOV_INT.HR_MOV_INT)) DH_MOV_INT,
                UNIDADE_DESTINO.CD_UNID_INT,
                UNIDADE_DESTINO.DS_UNID_INT,
                MOV_INT.TP_MOV,
                LEITO_DESTINO.CD_LEITO,
                LEITO_DESTINO.DS_LEITO,
                NVL(LEITO_DESTINO.SN_EXTRA,'N') SN_EXTRA,
                MOV_INT.CD_ATENDIMENTO
              FROM
                DBAMV.MOV_INT
                INNER JOIN DBAMV.LEITO LEITO_DESTINO ON MOV_INT.CD_LEITO = LEITO_DESTINO.CD_LEITO
                INNER JOIN DBAMV.UNID_INT UNIDADE_DESTINO ON LEITO_DESTINO.CD_UNID_INT = UNIDADE_DESTINO.CD_UNID_INT
              WHERE
                1=1
                AND MOV_INT.TP_MOV IN ('I','O')) mov_destino on NVL(dados.cd_mov_int_destino,dados.cd_mov_int_origem) =  mov_destino.cd_mov_int

WHERE DADOS.DH_ENTRADA BETWEEN '01/01/2024' AND '30/09/2024'
group by 
UPPER(TO_CHAR(DADOS.DH_ENTRADA,'d')||'-'||TO_CHAR(DADOS.DH_ENTRADA,'DAY')),
to_char(trunc(sysdate) + rownum/24, 'HH24')
ORDER BY 1,2 ASC

