select *
from LOG_AUDITORIA_TABELA
WHERE CD_TABELA = 'ATENDIME'
ORDER BY DH_REGISTRO DESC;

SELECT * FROM AUDIT_TABELA_AUDITORIA;

SELECT * FROM REGISTRO_AUDITORIA
WHERE CD_USUARIO_REGISTRO_AUDITORIA = 'FERNANDA.SLIMA'
AND TO_CHAR(TZ_REGISTRO_AUDITORIA,'DD/MM/YYYY') = '03/12/2025'
ORDER BY CD_REGISTRO_AUDITORIA DESC;


SELECT *
FROM USUARIO_ULTIMO_ACESSO
WHERE CD_USUARIO = 'FERNANDA.SLIMA';

SELECT *
FROM DISPOSITIVO_USUARIO_ACESSO;

SELECT *
FROM LOG_ACESSO_PEP
WHERE NM_USUARIO_LOG_ACESSO_PEP = 'FERNANDA.SLIMA';

select *
from LOG_RASTREABILIDADE;

SELECT *
FROM PW_LOG_ACAO_ADM_ITEM;

select *
from DBASGU.USUARIOS
where cd_usuario = 'FERNANDA.SLIMA';
