DECLARE
  CPROCEDIMENTO VARCHAR2(200);
  DDATAREFER DATE;
  DHORAREFER DATE;
  NCODCONVENIO NUMBER;
  NCODPLANO NUMBER;
  CTIPOATEND VARCHAR2(200);
  NCODTIPOACO NUMBER;
  CTPATIMED VARCHAR2(200);
  NVLPERCIRMULT NUMBER;
  CRETMSG VARCHAR2(200);
  NVLOPER NUMBER;
  NVLHONOR NUMBER;
  NVLFILME NUMBER;
  NVLPORTE NUMBER;
  NVLCHTOTAL NUMBER;
  NVLCHHONOR NUMBER;
  NVLTAXA NUMBER;
  NVLDESCONTO NUMBER;
  NVALPROCED NUMBER;
  NQTDE NUMBER;
  NVLRTOTAL NUMBER;
  NREGRA NUMBER;
  NPERCFRANQUIA NUMBER;
  NCDFRANQUIA NUMBER;
  NCDINDICE NUMBER;
  NCDREGRAACOP NUMBER;
  CPROFATEXCED VARCHAR2(200);
  CTPCONVENIO VARCHAR2(200);
  NCDCONVACOP NUMBER;
  NCDPLANACOP NUMBER;
  BPROCESSARVALOR BOOLEAN;
  PNCDPRESTADOR NUMBER;
  PNCDSETOR NUMBER;
  NCDCONTA NUMBER;
  NCDLANCAMENTO NUMBER;
  v_Return NUMBER;
BEGIN
  CPROCEDIMENTO := NULL;
  DDATAREFER := NULL;
  DHORAREFER := NULL;
  NCODCONVENIO := NULL;
  NCODPLANO := NULL;
  CTIPOATEND := NULL;
  NCODTIPOACO := NULL;
  CTPATIMED := NULL;
  NVLPERCIRMULT := NULL;
  CRETMSG := NULL;
  NVLOPER := NULL;
  NVLHONOR := NULL;
  NVLFILME := NULL;
  NVLPORTE := NULL;
  NVLCHTOTAL := NULL;
  NVLCHHONOR := NULL;
  NVLTAXA := NULL;
  NVLDESCONTO := NULL;
  NVALPROCED := NULL;
  NQTDE := NULL;
  NVLRTOTAL := NULL;
  NREGRA := NULL;
  NPERCFRANQUIA := NULL;
  NCDFRANQUIA := NULL;
  NCDINDICE := NULL;
  NCDREGRAACOP := NULL;
  CPROFATEXCED := NULL;
  CTPCONVENIO := NULL;
  NCDCONVACOP := NULL;
  NCDPLANACOP := NULL;
  BPROCESSARVALOR := NULL;
  PNCDPRESTADOR := NULL;
  PNCDSETOR := NULL;
  NCDCONTA := NULL;
  NCDLANCAMENTO := NULL;

  v_Return := VAL_PROC_FFCV(
    CPROCEDIMENTO => CPROCEDIMENTO,
    DDATAREFER => DDATAREFER,
    DHORAREFER => DHORAREFER,
    NCODCONVENIO => NCODCONVENIO,
    NCODPLANO => NCODPLANO,
    CTIPOATEND => CTIPOATEND,
    NCODTIPOACO => NCODTIPOACO,
    CTPATIMED => CTPATIMED,
    NVLPERCIRMULT => NVLPERCIRMULT,
    CRETMSG => CRETMSG,
    NVLOPER => NVLOPER,
    NVLHONOR => NVLHONOR,
    NVLFILME => NVLFILME,
    NVLPORTE => NVLPORTE,
    NVLCHTOTAL => NVLCHTOTAL,
    NVLCHHONOR => NVLCHHONOR,
    NVLTAXA => NVLTAXA,
    NVLDESCONTO => NVLDESCONTO,
    NVALPROCED => NVALPROCED,
    NQTDE => NQTDE,
    NVLRTOTAL => NVLRTOTAL,
    NREGRA => NREGRA,
    NPERCFRANQUIA => NPERCFRANQUIA,
    NCDFRANQUIA => NCDFRANQUIA,
    NCDINDICE => NCDINDICE,
    NCDREGRAACOP => NCDREGRAACOP,
    CPROFATEXCED => CPROFATEXCED,
    CTPCONVENIO => CTPCONVENIO,
    NCDCONVACOP => NCDCONVACOP,
    NCDPLANACOP => NCDPLANACOP,
    BPROCESSARVALOR => BPROCESSARVALOR,
    PNCDPRESTADOR => PNCDPRESTADOR,
    PNCDSETOR => PNCDSETOR,
    NCDCONTA => NCDCONTA,
    NCDLANCAMENTO => NCDLANCAMENTO
  );
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('v_Return = ' || v_Return);
*/ 
  :v_Return := v_Return;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('CRETMSG = ' || CRETMSG);
*/ 
  :CRETMSG := CRETMSG;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('NVLOPER = ' || NVLOPER);
*/ 
  :NVLOPER := NVLOPER;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('NVLHONOR = ' || NVLHONOR);
*/ 
  :NVLHONOR := NVLHONOR;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('NVLFILME = ' || NVLFILME);
*/ 
  :NVLFILME := NVLFILME;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('NVLPORTE = ' || NVLPORTE);
*/ 
  :NVLPORTE := NVLPORTE;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('NVLCHTOTAL = ' || NVLCHTOTAL);
*/ 
  :NVLCHTOTAL := NVLCHTOTAL;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('NVLCHHONOR = ' || NVLCHHONOR);
*/ 
  :NVLCHHONOR := NVLCHHONOR;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('NVLTAXA = ' || NVLTAXA);
*/ 
  :NVLTAXA := NVLTAXA;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('NVLDESCONTO = ' || NVLDESCONTO);
*/ 
  :NVLDESCONTO := NVLDESCONTO;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('NVLRTOTAL = ' || NVLRTOTAL);
*/ 
  :NVLRTOTAL := NVLRTOTAL;
--rollback; 
END;
