-- SELECIONAR MODULOS NO SISTEMA

SELECT * FROM DBASGU.AUT_MOD AM
       INNER JOIN DBASGU.USUARIOS U
             ON U.CD_USUARIO = AM.CD_USUARIO
       INNER JOIN DBASGU.MODULOS M
             ON M.CD_MODULO = AM.CD_MODULO
       INNER JOIN DBASGU.PAPEL_MOD PM
             ON PM.CD_MODULO = M.CD_MODULO
       INNER JOIN DBASGU.PAPEL P
             ON P.CD_PAPEL = PM.CD_PAPEL
WHERE AM.CD_MODULO = 'M_PED_RX'





SELECT * FROM DBAMV.PW_PERFIL_MODULO PERM 
       INNER JOIN DBAMV.PERFIL_AMBULATORIAL PEAM
             ON PEAM.CD_PERFIL_AMBULATORIAL = PERM.CD_PERFIL_AMBULATORIAL
WHERE PERM.CD_PERFIL_MODULO IN (SELECT PPM.CD_PERFIL_MODULO_PAI
          FROM DBAMV.PERFIL_AMBULATORIAL PA
         INNER JOIN DBAMV.PW_PERFIL_MODULO PPM
            ON PPM.CD_PERFIL_AMBULATORIAL = PA.CD_PERFIL_AMBULATORIAL
         INNER JOIN  DBAMV.PW_PERFIL_MODULO_PARAMETRO PPMP
            ON PPMP.CD_PERFIL_MODULO = PPM.CD_PERFIL_MODULO
         WHERE PPMP.NM_VALOR = '1160' OR PPMP.NM_VALOR = '1037')

/PEP/



