--SELECT * FROM gv$session;
/
--CALL DBMS_APPLICATION_INFO.SET_CLIENT_INFO('LimpaSessao');
BEGIN 
--  ALTER SYSTEM ENABLE RESTRICTED SESSION; 
  FOR X IN ( 
    SELECT SID,SERIAL# 
    FROM v$session 
    --WHERE CLIENT_INFO != 'LimpaSessao'
    WHERE PROGRAM <> 'SQL Developer' AND STATUS = 'INACTIVE'
    ORDER BY STATUS DESC, SERVICE_NAME, MACHINE
    ) LOOP 
    EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || X.SID || ',' || X.SERIAL# || ''' IMMEDIATE'; 
  END LOOP; 
END;
/
