SELECT 
'ALTER SYSTEM KILL SESSION ''' || SID || ',' || SERIAL# || ''';' AS Comando
--,SID,SERIAL#,CLIENT_INFO,STATUS
FROM v$session 
WHERE PROGRAM <> 'SQL Developer'
-- AND STATUS = 'INACTIVE'
-- AND STATUS = 'KILLED'
ORDER BY STATUS DESC, SERVICE_NAME, MACHINE
;

-- SERVICE_NAME, TERMINAL, MACHINE, USERNAME, PROGRAM, STATUS, SID
SELECT SID, SERIAL#, SERVICE_NAME, TERMINAL, MACHINE, USERNAME, PROGRAM, STATUS
FROM v$session
WHERE PROGRAM <> 'SQL Developer' --MACHINE <> 'INCN100'
ORDER BY STATUS DESC, SERVICE_NAME, MACHINE
;

SELECT Count(*)
FROM v$session
;

SELECT SID,SERIAL#,STATUS,SERVER
   FROM V$SESSION
   WHERE MACHINE <> 'INCN100';