-- ALTA MELHORADA

SELECT *
FROM atendime
WHERE cd_paciente in ('325008', '337664')  AND cd_atendimento in ('1101067', '1116440');
/

SELECT *
from mot_alt
/

ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_ATENDIMENTO DISABLE;
ALTER TRIGGER MVINTEGRA.TRG_IMVW_OUT_ATENDIMENTO DISABLE;


SELECT *
FROM atendime
WHERE CD_PACIENTE = '337664' AND cd_atendimento = '1116440';


ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_ATENDIMENTO ENABLE;
ALTER TRIGGER MVINTEGRA.TRG_IMVW_OUT_ATENDIMENTO ENABLE;


UPDATE atendime
SET cd_mot_alt = '',  dt_alta = '', hr_alta = ''
WHERE CD_PACIENTE = '337664' AND cd_atendimento = '1116440';


ALTER TRIGGER MVINTEGRA.TRG_IMVW_SAI_ATENDIMENTO ENABLE;
ALTER TRIGGER MVINTEGRA.TRG_IMVW_OUT_ATENDIMENTO ENABLE
/

/
ALTER TRIGGER DBAMV.TRG_ATENDIME DISABLE;

UPDATE atendime
SET cd_mot_alt = 1,
    dt_alta = TO_DATE('03/01/2026 00:00:00', 'DD/MM/YYYY HH24:MI:SS'),
    hr_alta = TO_DATE('03/01/2026 11:18:32', 'DD/MM/YYYY HH24:MI:SS')
WHERE CD_PACIENTE = '337664' AND cd_atendimento = '1116440';

ALTER TRIGGER DBAMV.TRG_ATENDIME ENABLE;
/

