SELECT DISTINCT TISS_VERSAO_CBOS.CD_CBOS, CONVENIO_CONF_TISS.cd_convenio,
				ESPECIALID.CD_ESPECIALID CD_ESPECIALIDIDADE, 
				ESPECIALID.DS_ESPECIALID DS_ESPECIALIDIDADE 	
FROM DBAMV.TISS_VERSAO_CBOS, 
				DBAMV.ESPECIALID, 
				DBAMV.CONVENIO_CONF_TISS 
WHERE ESPECIALID.CD_ESPECIALID = TISS_VERSAO_CBOS.CD_ESPECIALID 
				AND TISS_VERSAO_CBOS.CD_VERSAO_TISS = CONVENIO_CONF_TISS.CD_VERSAO_TISS 
				AND SubStr( CONVENIO_CONF_TISS.cd_versao_tiss,1,1 ) = '2' 
				AND CONVENIO_CONF_TISS.cd_convenio = 21
            	AND TISS_VERSAO_CBOS.CD_CBOS = '225125';
------

SELECT * FROM  CONVENIO_CONF_TISS
------

SELECT * FROM CONVENIO_CONF_TISS WHERE cd_convenio =21--  ORDER BY 1 desc
------

SELECT * FROM ped_lab ORDER BY 1 desc
------

SELECT substr(cd_versao_tiss,1,1) CD_VERSAO_TISS FROM dbamv.convenio_conf_tiss WHERE cd_convenio = 2
-------

SELECT DISTINCT TISS_VERSAO_CBOS.CD_CBOS,CONVENIO_CONF_TISS.cd_versao_tiss, CONVENIO_CONF_TISS.cd_convenio, 
				ESPECIALID.CD_ESPECIALID CD_ESPECIALIDIDADE, 
				ESPECIALID.DS_ESPECIALID DS_ESPECIALIDIDADE 	
FROM DBAMV.TISS_VERSAO_CBOS, 
	 			DBAMV.ESPECIALID, 
	 			DBAMV.CONVENIO_CONF_TISS 
WHERE ESPECIALID.CD_ESPECIALID = TISS_VERSAO_CBOS.CD_ESPECIALID 
				AND TISS_VERSAO_CBOS.CD_VERSAO_TISS = CONVENIO_CONF_TISS.CD_VERSAO_TISS 
				AND SubStr( CONVENIO_CONF_TISS.cd_versao_tiss,1,1 ) = '2'; 
------

SELECT * FROM ped_rx ORDER BY 1 desc
------

SELECT * FROM ped_lab ORDER BY 1 desc
------

SELECT * FROM TISS_VERSAO_CBOS
------

select * from dbasgu.modulos where cd_modulo like '%cad_cons%'
------
