SELECT * FROM ped_lab ORDER BY 1 DESC

SELECT * FROM PED_RX ORDER BY 1 DESC



      SELECT DISTINCT TISS_VERSAO_CBOS.CD_CBOS,
										        ESPECIALID.CD_ESPECIALID CD_ESPECIALIDIDADE,
										        ESPECIALID.DS_ESPECIALID DS_ESPECIALIDIDADE
										   FROM DBAMV.TISS_VERSAO_CBOS,
										        DBAMV.ESPECIALID,
										        DBAMV.CONVENIO_CONF_TISS
										  WHERE ESPECIALID.CD_ESPECIALID = TISS_VERSAO_CBOS.CD_ESPECIALID
										    AND TISS_VERSAO_CBOS.CD_VERSAO_TISS = CONVENIO_CONF_TISS.CD_VERSAO_TISS
										    AND SubStr( CONVENIO_CONF_TISS.cd_versao_tiss,1,1 ) = '2'
										   -- AND CONVENIO_CONF_TISS.cd_convenio = :P_CD_CONVENIO


SELECT * from usuarios WHERE nm_usuario LIKE '%Juli%'

select * FROM prestador_externo WHERE nm_pres_ext LIKE 'MARIANA PEDRINI UEBEL'

