SELECT * FROM PACIENTE WHERE Nm_paciente LIKE 'MARCIA PAULA DE MORAIS MIRANDA';

SELECT * FROM PACIENTE WHERE Nm_paciente LIKE '%MARCIA PAULA%';

SELECT * FROM PACIENTE WHERE NM_MAE LIKE 'EMILIA DE BIASE MORAIS';