SELECT * FROM (

SELECT
ATENDIME.CD_PRESTADOR,
ATENDIME.CD_CONVENIO,
PRESTADOR.NM_PRESTADOR,
CONVENIO.NM_CONVENIO,
DS_ESPECIALID ESPECIALIDADE,
	round(Decode ( PRE_MED.CD_PRE_MED, NULL , 0, DECODE(nvl(dbamv.pkg_mv2000.le_configuracao('PSIH', 'SN_DOSE_PRESCRICAO'),'N'), 'N', DBAMV.FNC_PSIH_RETORNA_DOSE(ATENDIME.CD_ATENDIMENTO,ITPRE_MED.CD_PRE_MED,PRODUTO.CD_PRODUTO,SOLSAI_PRO.CD_SOLSAI_PRO ), DBAMV.FNC_PSIH_RETORNA_DOSE(ATENDIME.CD_ATENDIMENTO,ITPRE_MED.CD_PRE_MED,PRODUTO.CD_PRODUTO,ITPRE_MED.CD_ITPRE_MED ) ) ),3) NR_DOSE,
DECODE(ATENDIME.TP_ATENDIMENTO ,'A',1,'U',2,'I',3,'E',4,'H',5) TIPO_ATENDIMENTO,
Decode(ATENDIME.TP_ATENDIMENTO, 'U', 'URGENCIA', 'I', 'INTERNACAO', 'A', 'AMBULATORIAL', 'E', 'EXTERNO') TIPO,
COUNT(*)

FROM
DBAMV.ATENDIME,
DBAMV.PRESTADOR,
DBAMV.CONVENIO,
DBAMV.ESPECIALID,
DBAMV.ESP_MED

WHERE CONVENIO.CD_CONVENIO  =  ATENDIME.CD_CONVENIO
  AND PRESTADOR.CD_PRESTADOR(+) = ATENDIME.CD_PRESTADOR
  AND ATENDIME.CD_MULTI_EMPRESA IN ({V_EMPRESA_AUX})
  AND ATENDIME.CD_CONVENIO IN ({V_CONVENIO_AUX})
  AND ESP_MED.CD_ESPECIALID=ESPECIALID.CD_ESPECIALID
  AND PRESTADOR.CD_PRESTADOR=ESP_MED.CD_PRESTADOR
  AND ESP_MED.SN_ESPECIAL_PRINCIPAL = 'S'
  AND TO_CHAR(ATENDIME.DT_ATENDIMENTO,'MM/YYYY') = '{V_COMPETENCIA}'

GROUP BY
PRESTADOR.NM_PRESTADOR,
ATENDIME.CD_PRESTADOR,
CONVENIO.NM_CONVENIO,
ATENDIME.CD_CONVENIO,
DECODE(ATENDIME.TP_ATENDIMENTO ,'A',1,'U',2,'I',3,'E',4,'H',5),
Decode(ATENDIME.TP_ATENDIMENTO, 'U', 'URGENCIA', 'I', 'INTERNACAO', 'A', 'AMBULATORIAL', 'E', 'EXTERNO'),
DS_ESPECIALID

)
WHERE TIPO_ATENDIMENTO IN ({V_ATENDIMENTO_AUX})

ORDER BY NM_PRESTADOR, CD_PRESTADOR