WITH ITAMB_MAX AS (
    SELECT
        CD_ATENDIMENTO,
        CD_PRO_FAT,
        MAX(VL_UNITARIO) AS MAX_VALOR
    FROM ITREG_AMB
    WHERE CD_ATENDIMENTO IN (
        SELECT CD_ATENDIMENTO
        FROM ATENDIME
        WHERE DT_ATENDIMENTO >= TO_DATE('2024-10-01', 'YYYY-MM-DD') -- Filtro para atendimentos a partir de 01/10/2024
    )
    GROUP BY CD_ATENDIMENTO, CD_PRO_FAT
),
ITAMB_FILTRADO AS (
    SELECT
        A.CD_ATENDIMENTO,
        A.CD_PRO_FAT,
        A.VL_UNITARIO,
        A.CD_PRESTADOR
    FROM ITREG_AMB A
    INNER JOIN ITAMB_MAX B
        ON A.CD_ATENDIMENTO = B.CD_ATENDIMENTO
        AND A.CD_PRO_FAT = B.CD_PRO_FAT
        AND A.VL_UNITARIO = B.MAX_VALOR
)
SELECT DISTINCT
    PX.DT_PEDIDO AS DATA_PEDIDO,
    PX.CD_ATENDIMENTO AS ATENDIMENTO,
    ORI.DS_ORI_ATE AS ORIGEM,
    PAC.NM_PACIENTE AS PACIENTE,
    PX.CD_CONVENIO AS CONVENIO,
    CONV.NM_CONVENIO AS NOME_CONVENIO,
    PX.CD_SETOR AS CD_SOLICITANTE,
    SETOR.NM_SETOR AS SETOR_SOLICITANTE,
    PX.CD_PED_RX AS PEDIDO,
    ITRX.CD_EXA_RX AS EXAME_LAUDO,
    ERX.DS_EXA_RX AS DS_EXAME,
    COALESCE(PRST_SOLICITANTE.NM_PRESTADOR, 'M DICO PRESTADOR EXTERNO') AS MEDICO_SOLICITANTE,
    PRST.NM_PRESTADOR AS MEDICO_LAUDO,
    PRST_ASS.NM_PRESTADOR AS MEDICO_ASSINATURA,
    PRST_AMB.NM_PRESTADOR AS MEDICO_FATURADO,
    ITAMB.CD_PRO_FAT AS PROCEDIMENTO,
    CASE
        WHEN ITAMB.VL_UNITARIO IS NOT NULL AND PRST_AMB.NM_PRESTADOR IS NOT NULL THEN ITAMB.VL_UNITARIO
        ELSE NULL
    END AS VALOR_UNITARIO
FROM PED_RX PX
INNER JOIN ATENDIME AT
    ON AT.CD_ATENDIMENTO = PX.CD_ATENDIMENTO
  --  AND AT.DT_ATENDIMENTO >= TO_DATE('2024-10-01', 'YYYY-MM-DD') -- Filtro para atendimentos a partir de 01/10/2024
INNER JOIN PACIENTE PAC
    ON PAC.CD_PACIENTE = AT.CD_PACIENTE
INNER JOIN ITPED_RX ITRX
    ON ITRX.CD_PED_RX = PX.CD_PED_RX
INNER JOIN LAUDO_RX LRX
    ON LRX.CD_PED_RX = PX.CD_PED_RX
INNER JOIN CONVENIO CONV
    ON CONV.CD_CONVENIO = PX.CD_CONVENIO
INNER JOIN SETOR SETOR
    ON PX.CD_SETOR = SETOR.CD_SETOR
INNER JOIN EXA_RX ERX
    ON ITRX.CD_EXA_RX = ERX.CD_EXA_RX
INNER JOIN ORI_ATE ORI
    ON AT.CD_ORI_ATE = ORI.CD_ORI_ATE
LEFT JOIN PRESTADOR PRST_ASS
    ON PRST_ASS.CD_PRESTADOR = LRX.CD_PRESTADOR_ASSINATURA
LEFT JOIN PRESTADOR PRST
    ON PRST.CD_PRESTADOR = ITRX.CD_PRESTADOR
LEFT JOIN ITAMB_FILTRADO ITAMB
    ON ITAMB.CD_ATENDIMENTO = AT.CD_ATENDIMENTO
    AND ITAMB.CD_PRO_FAT = ERX.EXA_RX_CD_PRO_FAT
LEFT JOIN PRESTADOR PRST_AMB
    ON PRST_AMB.CD_PRESTADOR = ITAMB.CD_PRESTADOR
LEFT JOIN PRESTADOR PRST_SOLICITANTE
    ON PRST_SOLICITANTE.CD_PRESTADOR = PX.CD_PRESTADOR
WHERE ITAMB.VL_UNITARIO IS NOT NULL
  AND PRST_AMB.NM_PRESTADOR IS NOT NULL
  AND AT.CD_ATENDIMENTO = 340120 -- Filtro espec fico